-- Clean expanded employment-law quiz question bank.
-- Keeps text question ids such as l10-q1, rebalances answer positions,
-- removes obvious duplicates by replacing them with distinct questions, and
-- corrects section references that had drifted from the Employment Code Act.

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'quiz_questions'
      and column_name = 'id'
      and data_type = 'uuid'
  ) then
    alter table public.quiz_questions
      alter column id drop default,
      alter column id type text using id::text;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'quiz_attempt_sessions'
      and column_name = 'question_ids'
      and data_type = 'ARRAY'
      and udt_name = '_uuid'
  ) then
    alter table public.quiz_attempt_sessions
      alter column question_ids type text[] using question_ids::text[];
  end if;
end $$;

alter table public.quiz_questions
  add column if not exists updated_at timestamptz not null default now();

insert into public.quiz_questions (
  id,
  level,
  scenario,
  question,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_index,
  explanation,
  act_reference,
  case_reference,
  active
) values
-- LEVEL 1: FOUNDATIONS
('l1-q1', 1, 'A member of the Zambia Police Service claims ordinary coverage under the Employment Code Act, 2019.', 'What is the best starting legal answer?', 'The Act automatically applies to every worker in Zambia without exception', 'The Act applies only if the person has worked for twelve months', 'The Act does not apply to members of the Zambia Police Service', 'The Act applies only if the Labour Commissioner agrees in writing', 2, 'Section 2 excludes members of the Zambia Police Service from the Act.', 'Employment Code Act, 2019, s.2(1)(b)', '', true),
('l1-q2', 1, 'A company pays one woman less than a man doing work of equal value even though they perform the same duties at the same level.', 'Which section is most directly engaged by this scenario?', 'Section 5 on non-discrimination and equal wages for work of equal value', 'Section 27 on probation', 'Section 55 on redundancy', 'Section 73 on gratuity', 0, 'Section 5 prohibits discrimination and specifically requires equal wages for work of equal value.', 'Employment Code Act, 2019, s.5(1)-(4)', '', true),
('l1-q3', 1, 'An employer keeps re-engaging the same worker on temporary terms for eight months to do a core, regular job with fixed weekly hours and no valid temporary reason.', 'What is the strongest legal concern?', 'The employer has created a lawful apprenticeship', 'The worker loses all rights because the contract was temporary', 'The arrangement may amount to prohibited casualisation', 'The worker automatically becomes a director of the company', 2, 'Using temporary or fixed arrangements without a permissible reason for work that is permanent in nature may amount to prohibited casualisation.', 'Employment Code Act, 2019, s.7', '', true),
('l1-q4', 1, 'A person is compelled to work under threats and cannot freely leave the arrangement.', 'Which core statutory prohibition is most directly raised?', 'Only a wage record breach', 'Only a minor overtime issue', 'A probation extension issue', 'A prohibition against forced labour', 3, 'The Act prohibits forced labour and makes contravention an offence.', 'Employment Code Act, 2019, s.8', '', true),
('l1-q5', 1, 'An employer issues a contract lasting for two years with a fixed end date agreed by both parties.', 'How does the Act most accurately classify that contract?', 'A long-term contract', 'A permanent contract only', 'A casual engagement', 'A public holiday arrangement', 0, 'A contract for a period exceeding twelve months whose termination is fixed in advance is a long-term contract.', 'Employment Code Act, 2019, s.3', '', true),
('l1-q6', 1, 'An employer engages a worker for a specific task expected to last three weeks.', 'What type of contract is this under the Act?', 'A permanent contract', 'A long-term contract', 'A casual contract only', 'A short-term contract', 3, 'A contract for a specific task or period not exceeding twelve months is a short-term contract.', 'Employment Code Act, 2019, s.3', '', true),
('l1-q7', 1, 'An employer says it can dictate any working terms because Zambia has no minimum employment standards.', 'Which statement best corrects that view?', 'Only the Constitution governs employment terms', 'The employer is correct; working terms are purely private', 'Minimum standards apply only in the mining sector', 'The Employment Code Act sets minimum standards that apply regardless of contract', 3, 'The Employment Code Act sets statutory minimums and more favourable terms may apply over less favourable contractual terms.', 'Employment Code Act, 2019, s.127', '', true),
('l1-q8', 1, 'An employer wants to engage someone for agricultural harvesting work that occurs only during a specific season each year.', 'Which contract type best fits that arrangement under the Act?', 'A permanent contract', 'A seasonal employment contract', 'A long-term contract', 'A casual contract', 1, 'Work that recurs during a specific season is seasonal employment.', 'Employment Code Act, 2019, s.3', '', true),
('l1-q9', 1, 'A worker with no fixed end date and no specific task limitation has worked for three years under the same employer.', 'What employment type does the Act recognise here?', 'Short-term employment', 'Seasonal employment', 'Apprenticeship only', 'Permanent employment', 3, 'Employment without a fixed term or specific task limitation is permanent employment.', 'Employment Code Act, 2019, s.3', '', true),
('l1-q10', 1, 'A student asks what the term "employee" means under the Employment Code Act.', 'Which of the following is correct about the definition of "employee"?', 'Only permanent full-time workers are employees', 'Only unionised workers', 'Any person who enters into a contract of employment for wages or commission, including casual employees and qualifying apprentices', 'Only persons earning above minimum wage', 2, 'Section 3 defines employee broadly and excludes independent contractors and piece workers.', 'Employment Code Act, 2019, s.3', '', true),
('l1-q11', 1, 'A law student asks which statute is most important for regulating individual employment relations in Zambia.', 'Which Act is the primary legislation regulating employment conditions in Zambia?', 'The Constitution of Zambia', 'The Workers Compensation Act', 'The Industrial and Labour Relations Act', 'The Employment Code Act, No. 3 of 2019', 3, 'The Employment Code Act is the central statute for basic employment conditions and individual employment rights.', 'Employment Code Act, 2019', '', true),
('l1-q12', 1, 'An employer asks whether the Employment Code Act applies to all workers in Zambia.', 'Which workers are excluded from the Employment Code Act?', 'All private sector workers', 'Only agricultural workers', 'Members of the Defence Force, Zambia Police Service, Correctional Service, and Security Intelligence Service', 'All workers earning above minimum wage', 2, 'Section 2 excludes these services, with a limited exception for locally engaged civilian employees in the Defence Force.', 'Employment Code Act, 2019, s.2', '', true),
('l1-q13', 1, 'A new HR officer asks about the purpose of the Employment Code Act.', 'What is the main purpose of the Employment Code Act?', 'To abolish all employment contracts', 'To regulate employment and provide basic conditions of employment', 'To eliminate all trade unions', 'To set maximum wages for all workers', 1, 'The Act regulates employment, contracts, wages, benefits, employee welfare, employment agencies, and related matters.', 'Employment Code Act, 2019, long title', '', true),
('l1-q14', 1, 'An employer says Zambia has no binding international labour obligations because international law is not automatically enforceable domestically.', 'What is the cautious position on international labour standards in Zambia?', 'International instruments are directly enforceable in all employment disputes', 'Zambia has never ratified any ILO conventions', 'International law has no role in Zambian employment law', 'Ratified international instruments are generally persuasive until domesticated, but courts may take judicial notice of them', 3, 'Zambia is generally dualist, so ratified instruments normally need domestication before direct enforcement, but courts may consider them as persuasive authority.', 'Constitution of Zambia; ILO Conventions', 'Sara Longwe v Inter-Continental Hotels [1993]', true),
('l1-q15', 1, 'An employee asks what constitutes a valid reason for termination under the Employment Code Act.', 'Under section 52(2), what are the three categories of valid reasons for termination?', 'Only gross misconduct', 'Conduct of the employee, capacity of the employee, or operational requirements of the undertaking', 'Only redundancy', 'Any reason the employer chooses', 1, 'Section 52(2) requires a valid reason connected with capacity, conduct, or operational requirements.', 'Employment Code Act, 2019, s.52(2)', '', true),
('l1-q16', 1, 'An employer wants to know if Zambia has ratified the core ILO conventions.', 'How many core ILO conventions has Zambia ratified?', 'Four', 'Six', 'Eight', 'Ten', 2, 'Zambia has ratified the eight fundamental ILO conventions traditionally treated as core labour standards.', 'ILO fundamental conventions', '', true),
('l1-q17', 1, 'A legal researcher asks which historical UK policy influenced early Zambian labour law.', 'What was the UK policy of voluntarism in industrial relations?', 'Government set all wages by decree', 'Trade unions were illegal', 'Individual and collective bargaining largely determined wages and conditions', 'Only employers could set conditions', 2, 'Voluntarism relied heavily on bargaining rather than direct state prescription of all terms.', 'Labour Law in Zambia: An Introduction, Ch.1', '', true),
('l1-q18', 1, 'An employer says the Constitution is irrelevant to employment matters.', 'What is the constitutional status of the Constitution in Zambia?', 'The Constitution is the supreme law, and inconsistent written law, customary law, or practice is void to the extent of the inconsistency', 'Only the Employment Code Act matters', 'The Constitution only applies to government workers', 'The Constitution has no effect on employment', 0, 'The Constitution is the supreme law and invalidates inconsistent law or practice to the extent of inconsistency.', 'Constitution of Zambia, Art.1', '', true),
('l1-q19', 1, 'An employer asks whether the Apprenticeship Act applies to university students working during vacations to gain practical experience.', 'Does the Apprenticeship Act apply to university vacation work for experience?', 'Yes, all practical training is governed by the Apprenticeship Act', 'Only if the placement lasts more than six months', 'Only if the student is paid', 'No, the Act does not apply to university students doing vacation work to obtain experience', 3, 'The Apprenticeship Act excludes university students working during vacations to obtain experience.', 'Apprenticeship Act, Cap. 275', '', true),

-- LEVEL 10: WORKPLACE DISCIPLINE
('l10-q1', 10, 'An employer wants to dismiss a worker for stealing company equipment caught on CCTV.', 'Even where clear evidence exists, what procedural step must normally precede dismissal?', 'A fair disciplinary hearing at which the employee can respond', 'No procedure is needed when evidence is strong', 'A police conviction first', 'A warning letter followed by a six-month suspension', 0, 'Procedural fairness remains central even where misconduct evidence appears strong.', 'Employment Code Act, 2019, s.52(3)', 'Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116', true),
('l10-q2', 10, 'An employee receives a first warning for lateness and is immediately dismissed without prior progressive discipline.', 'Why is this dismissal likely to be unfair?', 'Only the Labour Commissioner can dismiss for rule infractions', 'The Act bans all warnings', 'First warnings always justify dismissal', 'Dismissal is disproportionate; progressive discipline should ordinarily be followed for minor infractions', 3, 'For minor misconduct, warnings and corrective steps are ordinarily expected before dismissal.', 'Employment Code Act, 2019, s.52', 'Labour Law in Zambia, Ch.5', true),
('l10-q3', 10, 'An employer suspends a worker without pay pending a disciplinary investigation.', 'What is the safer legal position on suspension pending investigation?', 'Suspension automatically terminates the contract', 'Suspension without pay is always allowed', 'Suspension should normally be on pay unless a statute, contract, or disciplinary rule permits otherwise', 'The employer may suspend without pay whenever convenient', 2, 'Suspension should follow the disciplinary rules applicable to the employee, and unpaid suspension needs clear legal or contractual authority.', 'Employment Code Act, 2019, s.49', 'Labour Law in Zambia, Ch.5', true),
('l10-q4', 10, 'An employee is charged with a criminal offence unrelated to employment. The employer dismisses them immediately.', 'Does a criminal charge alone justify immediate dismissal?', 'No, the employer must assess relevance to employment and still follow a fair process', 'Yes, any criminal charge allows instant dismissal', 'Yes, criminal charges are always gross misconduct', 'No, but the employer may cut wages while charges are pending', 0, 'A charge is not the same as proof of workplace misconduct; relevance and fair process still matter.', 'Employment Code Act, 2019, s.52', 'Labour Law in Zambia, Ch.5', true),
('l10-q5', 10, 'A disciplinary panel includes the employee''s direct line manager who witnessed the alleged misconduct and reported it.', 'What natural-justice principle is engaged here?', 'Only external adjudicators can rule on misconduct', 'The panel composition never affects validity', 'The rule against bias; a witness should not sit as a judge', 'None, managers must always sit on panels', 2, 'A person with a direct interest or witness role should not also be the decision-maker.', 'Employment Code Act, 2019, s.52(3)', 'Labour Law in Zambia, Ch.5', true),
('l10-q6', 10, 'An employee is dismissed for misconduct but the employer does not follow the disciplinary procedure in the contract.', 'Under Zambia National Provident Fund v Yekwenya Mbinwa Chirwa, what older common-law caution should HR remember?', 'Where a dismissible offence is proved, failure to follow procedure may not always make the dismissal wrongful under that authority', 'Procedure is never relevant in misconduct cases', 'Procedure is always mandatory regardless of all facts', 'Only probationary employees need a procedure', 0, 'The case is an older authority often cited for the proposition that a proven dismissible offence can affect the remedy and wrongful-dismissal analysis, though modern statutory fairness duties still require caution.', 'Employment Code Act, 2019, s.52', 'Zambia National Provident Fund v Yekwenya Mbinwa Chirwa [1986] ZR 70', true),
('l10-q7', 10, 'An employee is suspended pending an investigation into alleged theft.', 'What does section 49 of the Employment Code Act require regarding suspension?', 'Suspension is not permitted under any circumstances', 'Suspension requires Labour Commissioner approval', 'Suspension without pay is automatically lawful', 'Suspension must be done in accordance with the employer''s disciplinary rules applicable to the employee', 3, 'Section 49 ties suspension to the applicable disciplinary rules.', 'Employment Code Act, 2019, s.49', '', true),
('l10-q8', 10, 'An employer terminates a fixed-term contract employee six months before the contract end date without giving any reason.', 'What must the employer provide to justify early termination?', 'Only payment of wages for the notice period', 'Nothing, fixed-term contracts can be ended anytime', 'A valid reason connected with capacity, conduct, or operational requirements', 'Only thirty days notice', 2, 'Section 52(2) requires a valid reason for termination; expiry by effluxion of time is different from early termination.', 'Employment Code Act, 2019, s.52(2)', '', true),
('l10-q9', 10, 'An employer terminates an employee for poor performance but never provided feedback, training, or an opportunity to improve.', 'What must an employer generally show to justify termination for poor performance?', 'Poor performance alone always justifies dismissal', 'Only written warnings are required', 'No justification is needed for performance dismissals', 'The employee was given a fair opportunity to improve and dismissal was proportionate', 3, 'Capacity dismissals are stronger when the employer can show standards, feedback, support, and a fair chance to improve.', 'Employment Code Act, 2019, s.52(2)', 'Labour Law in Zambia, Ch.5', true),
('l10-q10', 10, 'An employer claims an employee resigned. The employee says they were forced to resign because working conditions had become intolerable.', 'What legal doctrine applies to this situation?', 'Constructive dismissal', 'Mutual separation only', 'Redundancy', 'A probation extension', 0, 'Constructive dismissal concerns resignation caused by the employer''s conduct making continued employment intolerable.', 'Employment Code Act, 2019, s.52', 'Chilanga Cement v Kasote Singogo [2009] ZMSC', true),
('l10-q11', 10, 'An employer wants to dismiss an employee for absenteeism. The employee provides medical certificates for all absences.', 'Can the employer still dismiss purely because the employee was absent?', 'Only if the employer suspects fraud without checking', 'Yes, any absence justifies dismissal', 'Not usually; valid medical certificates require the employer to consider sick leave, capacity, and fairness before dismissal', 'Yes, but only after six months of absences', 2, 'Certified medical absences engage sick leave and capacity analysis; dismissal is risky unless incapacity and fair process are properly established.', 'Employment Code Act, 2019, ss.38 and 52', '', true),
('l10-q12', 10, 'An employee admits a serious safety breach but asks for mitigation before sanction is decided.', 'What should a fair disciplinary process consider before dismissal?', 'Mitigation, seriousness, consistency, and proportionality of sanction', 'Only whether the manager is angry enough', 'Only the employee''s salary level', 'Nothing after admission', 0, 'Even where misconduct is admitted, sanction should be proportionate and consistent, with mitigation considered.', 'Employment Code Act, 2019, s.52(3)', 'Labour Law in Zambia, Ch.5', true),

-- LEVEL 11: DISCRIMINATION
('l11-q1', 11, 'An employer refuses to promote a qualified woman because of assumptions about her family responsibilities.', 'Which ground of discrimination is most directly at issue?', 'Discrimination on the ground of sex or gender', 'Discrimination based on working hours only', 'A neutral business decision with no legal concern', 'Discrimination based on educational qualifications', 0, 'Refusing promotion based on gender stereotypes is sex or gender discrimination.', 'Employment Code Act, 2019, s.5', '', true),
('l11-q2', 11, 'A worker with a disability is denied reasonable accommodation and is placed at a structural disadvantage compared to non-disabled colleagues.', 'What type of discrimination does this describe?', 'Direct discrimination only', 'No discrimination; disability is not protected', 'Indirect discrimination or failure to provide reasonable accommodation', 'Only a health-and-safety issue', 2, 'Failure to accommodate disability can amount to indirect discrimination and breach disability protections.', 'Employment Code Act, 2019, s.5; Persons with Disabilities Act, s.35', '', true),
('l11-q3', 11, 'A manager repeatedly makes sexually suggestive comments to a subordinate at work despite the subordinate''s clear discomfort.', 'How does the Employment Code Act characterise this conduct?', 'A minor workplace relationship issue only', 'A personal matter outside employment law', 'Only criminal if physical contact occurs', 'Sexual harassment, a prohibited form of workplace discrimination', 3, 'Unwelcome sexual comments or advances can amount to workplace sexual harassment.', 'Employment Code Act, 2019, s.5(6)', '', true),
('l11-q4', 11, 'An employer applies a facially neutral requirement that in practice excludes significantly more women than men with no business justification.', 'What concept does this illustrate?', 'Reverse discrimination', 'Direct discrimination', 'Indirect discrimination', 'Positive action', 2, 'Indirect discrimination arises when a neutral rule disproportionately disadvantages a protected group without objective justification.', 'Employment Code Act, 2019, s.5', 'Labour Law in Zambia, Ch.6', true),
('l11-q5', 11, 'An employer dismisses an employee after the employee discloses their HIV-positive status.', 'How does the Employment Code Act treat this dismissal?', 'It is prohibited discrimination on the ground of HIV status', 'Only the Workers Compensation Act governs this', 'The employer may always dismiss if the role requires physical fitness', 'The employer''s stated reason is always accepted by courts', 0, 'HIV status is a protected ground and dismissal on that ground is unlawful discrimination.', 'Employment Code Act, 2019, ss.5 and 95', '', true),
('l11-q6', 11, 'An employer promotes a less qualified man over a more qualified woman, saying the man needs the job more to support his family.', 'Which form of discrimination is most directly engaged?', 'Indirect discrimination based on working hours', 'Positive action for men', 'Direct discrimination based on sex', 'No discrimination; financial need is a valid basis for promotion', 2, 'Gender stereotypes about breadwinning are a direct sex-discrimination concern.', 'Employment Code Act, 2019, s.5(2)(a)', '', true),
('l11-q7', 11, 'An employer dismisses an employee who filed a complaint with the Labour Commissioner about unpaid wages.', 'What does section 52(4)(c) of the Employment Code Act say about this?', 'The employee must exhaust internal remedies first', 'Only false complaints are protected', 'The employer may dismiss for any reason during a complaint process', 'Termination based on filing a complaint or participating in proceedings against the employer is prohibited', 3, 'Retaliatory termination for asserting legal rights is prohibited.', 'Employment Code Act, 2019, s.52(4)(c)', '', true),
('l11-q8', 11, 'An employer applies a rule that all employees must work overtime every weekend. This disproportionately affects mothers with young children.', 'What type of discrimination may this represent?', 'Indirect discrimination if the neutral rule disproportionately affects a protected group without justification', 'No discrimination because the rule applies to everyone', 'Direct discrimination only', 'Positive action', 0, 'A neutral rule can still be discriminatory if its impact falls disproportionately on a protected group and cannot be justified.', 'Employment Code Act, 2019, s.5', 'London Underground Ltd v Edwards [1998]', true),
('l11-q9', 11, 'A female employee returns from maternity leave to find her position filled and no equivalent role offered.', 'Which combined statutory protections are most engaged?', 'Only the redundancy provisions', 'Maternity protection, non-discrimination, and fair dismissal procedure', 'Only the leave entitlement sections', 'Only the probation provisions', 1, 'The scenario engages maternity protection, sex discrimination, and fair dismissal together.', 'Employment Code Act, 2019, ss.5, 43 and 52', '', true),
('l11-q10', 11, 'An employer refuses to hire a qualified applicant because they have a physical disability that does not affect their ability to perform the job.', 'What does the Employment Code Act say about discrimination on grounds of disability?', 'Only visible disabilities are protected', 'Disability is not a protected ground', 'Section 5 prohibits discrimination on grounds of disability', 'Disability discrimination is permitted', 2, 'Disability is a listed prohibited ground of discrimination.', 'Employment Code Act, 2019, s.5(2)(a)', '', true),
('l11-q11', 11, 'An employer pays a Zambian employee less than an expatriate employee performing identical work with similar qualifications and responsibility.', 'What does the equal-pay principle require?', 'Equal wages for work of equal value unless a lawful justification exists', 'Expatriates can always be paid more based on nationality', 'Only citizens are protected by equal-pay provisions', 'The employer may set any wage differential', 0, 'Section 5 requires equal wages for work of equal value and prohibits nationality-based discrimination.', 'Employment Code Act, 2019, s.5(4)', '', true),
('l11-q12', 11, 'An employer only hires men for security guard positions, claiming women are not physically strong enough for the role.', 'What defence might the employer attempt to raise under section 5(3)?', 'The inherent-requirement defence, if the employer can prove the requirement is essential and proportionate', 'No defence exists in any sex-discrimination case', 'Affirmative action for men', 'Citizen priority', 0, 'The inherent-requirement defence is narrow and must be proved, not assumed.', 'Employment Code Act, 2019, s.5(3)(b)', '', true),
('l11-q13', 11, 'An employer implements a policy promoting women into management to address historical gender imbalance.', 'Is this necessarily discriminatory under section 5?', 'Yes, any gender-conscious measure is unlawful', 'Only if male employees object', 'Only if approved by the Labour Commissioner', 'No, affirmative-action measures consistent with equality may be permitted', 3, 'Section 5 permits affirmative-action measures designed to promote equality or eliminate discrimination.', 'Employment Code Act, 2019, s.5(3)(a)', '', true),

-- LEVEL 12: YOUNG PERSONS AND APPRENTICES
('l12-q1', 12, 'An employer wants to employ a child aged thirteen in a commercial shop during school holidays.', 'What is the general minimum contractual age under the Employment Code Act?', 'Twelve years', 'Fifteen years', 'Eighteen years', 'Sixteen years', 1, 'The Code generally sets fifteen as the minimum contractual age, while Part V contains specific child and young-person restrictions.', 'Employment Code Act, 2019, s.16', '', true),
('l12-q2', 12, 'An employer wants to have a seventeen-year-old work in a mine handling explosives.', 'Is this permissible under Zambian law?', 'No, hazardous work and the worst forms of labour are prohibited for children and young persons', 'Yes, if the minor is supervised', 'Yes, if parental consent is given', 'Yes, for mining specifically', 0, 'Mines are industrial undertakings and hazardous work/worst forms of labour are prohibited for children and young persons.', 'Employment Code Act, 2019, ss.80 and 83', '', true),
('l12-q3', 12, 'An employer requires a sixteen-year-old employee to work night shifts starting at 10 pm.', 'What does the law say about night work for young persons?', 'Night work is prohibited for young persons in industrial undertakings except in specified circumstances', 'Night work is freely permitted for all employees', 'Only persons under fifteen may not work nights', 'Night work restrictions apply only to females under eighteen', 0, 'Section 86 prohibits night work for young persons in industrial undertakings, subject to specific exceptions.', 'Employment Code Act, 2019, s.86', '', true),
('l12-q4', 12, 'An apprentice asks whether the Employment Code Act alone governs their formal training arrangement.', 'Which statute primarily governs formal apprenticeships in Zambia?', 'The Skills Development Levy Act', 'The Workers Compensation Act', 'The Employment Code Act, 2019 alone', 'The Apprenticeship Act, Chapter 275 of the Laws of Zambia', 3, 'Formal apprenticeships are principally governed by the Apprenticeship Act.', 'Apprenticeship Act, Cap. 275', '', true),
('l12-q5', 12, 'An employer wants to employ a fourteen-year-old in a light family agricultural task during school holidays.', 'What is the cautious legal answer?', 'Children aged thirteen to fifteen may only do light work if it is not harmful and does not prejudice schooling or training', 'Children cannot work in any undertaking in any circumstance', 'Only with a special permit from the Labour Commissioner', 'Only if the child has completed primary school', 0, 'Light work for children aged thirteen to fifteen is treated separately from ordinary employment and must not harm health, development, schooling, or training.', 'Employment Code Act, 2019, Part V', '', true),
('l12-q6', 12, 'A seventeen-year-old wants to work as an apprentice in a factory.', 'Under section 84, what must the employer have?', 'Either a contract of apprenticeship under the Apprenticeship Act or a certificate signed by an authorised officer', 'Nothing, because seventeen is above the minimum age', 'Only parental consent', 'Only a medical certificate', 0, 'Section 84 requires an apprenticeship contract or authorised officer certificate for a young person in an industrial undertaking.', 'Employment Code Act, 2019, s.84', '', true),
('l12-q7', 12, 'An employer hires a fifteen-year-old to work in a mine.', 'Is this permissible under Zambian law?', 'Yes, fifteen is the minimum contractual age for all work', 'No, mining is an industrial undertaking and hazardous work is prohibited for young persons', 'Yes, with parental consent', 'Yes, for mining specifically', 1, 'Minimum age for ordinary contracts does not authorise hazardous or prohibited industrial work.', 'Employment Code Act, 2019, ss.80, 81, 83 and 84', '', true),
('l12-q8', 12, 'An employer is found employing a twelve-year-old child in a commercial undertaking.', 'What is the maximum penalty under section 16(2) for contravening the minimum contractual age rule?', 'A fine not exceeding 500,000 penalty units or imprisonment not exceeding five years, or both', 'Only a warning for first offence', 'A fine not exceeding 10,000 penalty units', 'A fine not exceeding 50,000 penalty units', 0, 'Section 16(2) provides a serious penalty for contravention of the minimum contractual age provision.', 'Employment Code Act, 2019, s.16(2)', '', true),
('l12-q9', 12, 'An employer is convicted for employing a child or young person in the worst forms of labour.', 'What penalty does section 83(2) provide?', 'Only a warning', 'A fine not exceeding 500,000 penalty units', 'A fine not exceeding 200,000 penalty units or imprisonment not exceeding two years, or both', 'Imprisonment only, no fine', 2, 'Section 83(2) provides for a fine, imprisonment, or both.', 'Employment Code Act, 2019, s.83(2)', '', true),
('l12-q10', 12, 'An industrial undertaking employer asks what records must be kept for young persons employed.', 'What does section 85 require regarding a register of young persons?', 'Only names and ages', 'A register specifying names, dates of birth, dates of employment, and any other prescribed information', 'No records are required', 'Only copies of employment contracts', 1, 'Section 85 requires a register with specified details for young persons in industrial undertakings.', 'Employment Code Act, 2019, s.85', '', true),
('l12-q11', 12, 'An employer wants to know what counts as the worst forms of labour.', 'Which of the following is included?', 'Working more than forty hours per week', 'Working on public holidays', 'Working without a written contract', 'Slavery, debt bondage, forced labour, prostitution, illicit activities, or harmful work involving children or young persons', 3, 'The definition includes slavery-like practices, forced labour, sexual exploitation, illicit activities, and work likely to harm health, safety, or morals.', 'Employment Code Act, 2019, s.80', '', true),
('l12-q12', 12, 'A shop employer wants a fifteen-year-old to work very long days.', 'What extra caution applies to young shop workers?', 'There are no hour limits for young workers in shops', 'Young shop workers are subject to special limits under applicable minimum wage and shop-worker rules', 'Only miners have special limits', 'The rules apply only to unpaid work', 1, 'Sector orders may impose stricter limits for young workers, so minimum-age compliance is not the end of the analysis.', 'Minimum Wages and Conditions of Employment (Shop Workers) Order, 2011', '', true),

-- LEVEL 13: SOCIAL SECURITY
('l13-q1', 13, 'An employer has not been registering its employees with NAPSA since the company opened two years ago.', 'What is the employer''s primary obligation under NAPSA legislation?', 'Every employer must register and remit prescribed monthly contributions for eligible employees', 'Registration is optional for companies with fewer than twenty employees', 'NAPSA only covers public servants', 'Registration is required only at retirement', 0, 'Employers must register and remit monthly contributions for eligible employees.', 'National Pension Scheme Act', '', true),
('l13-q2', 13, 'An employer asks whether National Health Insurance registration is mandatory.', 'What does the National Health Insurance Act require?', 'NHIMA is voluntary for private sector employers', 'Only for companies with more than fifty employees', 'Only for the public sector', 'Mandatory registration and contributions for covered employers, employees, and other eligible persons', 3, 'The National Health Insurance Act establishes mandatory registration and contribution obligations.', 'National Health Insurance Act, 2018', '', true),
('l13-q3', 13, 'An employee is injured at work and asks what statutory scheme covers compensation for that injury.', 'Which legislation governs compensation for work-related injuries and diseases in Zambia?', 'The Employment Code Act, 2019', 'The Workers Compensation Act, No. 10 of 1999', 'The NAPSA Act', 'The Gender Equity and Equality Act', 1, 'The Workers Compensation Act governs compensation for occupational injury and disease.', 'Workers Compensation Act, No. 10 of 1999', '', true),
('l13-q4', 13, 'An employer has not paid the Skills Development Levy for two years.', 'Under which Act is the Skills Development Levy required?', 'The Employment Code Act', 'The Industrial and Labour Relations Act', 'The Skills Development Levy Act, No. 46 of 2016', 'The Penal Code', 2, 'The Skills Development Levy Act requires payment of the levy, subject to statutory exemptions.', 'Skills Development Levy Act, No. 46 of 2016', '', true),
('l13-q5', 13, 'An employer asks whether NAPSA contributions are required for a fixed-term contract employee who has worked for six months.', 'Are fixed-term employees covered by NAPSA?', 'No, only permanent employees are covered', 'Only after twelve months of continuous service', 'Yes, if they are eligible employees, regardless of contract type', 'Only if the employee earns above minimum wage', 2, 'NAPSA coverage is not limited to permanent employment.', 'National Pension Scheme Act', '', true),
('l13-q6', 13, 'An employer asks whether the Skills Development Levy applies to all employers.', 'What is the rate and broad applicability of the Skills Development Levy?', '1 percent of gross emoluments for all employers', 'No levy; it was repealed by the Employment Code Act', 'A flat fee of ZMW500 per employee per year', '0.5 percent of gross emoluments, subject to statutory exemptions', 3, 'The levy is generally 0.5 percent of gross emoluments, with statutory exemptions such as specified public bodies and low-turnover employers.', 'Skills Development Levy Act, No. 46 of 2016', '', true),
('l13-q7', 13, 'A self-employed consultant asks whether National Health Insurance applies only to employees.', 'Does the National Health Insurance Act require self-employed persons to register?', 'No, NHIMA only covers employees', 'Yes, covered adult citizens or residents include self-employed persons', 'Only self-employed professionals like lawyers and doctors', 'Only self-employed persons above a special earnings threshold', 1, 'The Act extends beyond formal employees and includes self-employed covered persons.', 'National Health Insurance Act, 2018', '', true),
('l13-q8', 13, 'An employer wants to know the retirement age for NAPSA pension eligibility.', 'What is the normal pensionable age under the National Pension Scheme Act?', '55 years', '58 years', '60 years', '65 years', 2, 'The normal pensionable age is generally sixty, with early and late retirement rules also relevant.', 'National Pension Scheme Act, s.18', '', true),
('l13-q9', 13, 'An employee is injured at work and asks whether fault automatically defeats a workers compensation claim.', 'When may compensation be payable despite employee misconduct?', 'Never; employee fault bars every claim', 'Only if the employer was also at fault', 'Only for minor misconduct', 'Where the statute preserves compensation, such as serious permanent disablement despite serious and wilful misconduct', 3, 'Workers compensation is statutory and may still be payable in specified cases despite misconduct.', 'Workers Compensation Act, 1999, s.41', '', true),
('l13-q10', 13, 'An employee receives workers compensation while also claiming sick-leave wages after an occupational injury.', 'How does the Employment Code Act coordinate sick-leave wages with workers compensation?', 'Both are always paid in full without adjustment', 'Wages payable during sick leave are reduced by the amount of workers compensation received', 'The employee must choose one forever', 'Only NAPSA decides the wage amount', 1, 'Section 38(4) reduces sick-leave wages by workers compensation received.', 'Employment Code Act, 2019, s.38(4)', 'Workers Compensation Act', true),
('l13-q11', 13, 'An employer asks whether NHIMA and NAPSA are the same scheme.', 'What is the best distinction?', 'They are the same fund under different names', 'NAPSA concerns pension/social security contributions, while NHIMA concerns national health insurance', 'NHIMA replaced NAPSA entirely', 'Both apply only to government employees', 1, 'NAPSA and NHIMA are separate statutory schemes with different purposes.', 'National Pension Scheme Act; National Health Insurance Act, 2018', '', true),
('l13-q12', 13, 'An employer deducts employee pension contributions but does not remit them.', 'What is the main legal risk?', 'No legal risk if deductions were made from pay', 'The employer may face statutory enforcement for failure to remit required contributions', 'The employee must sue only the bank', 'The obligation disappears after one month', 1, 'Deducting contributions does not satisfy the employer''s duty to remit them to the statutory scheme.', 'National Pension Scheme Act', '', true),

-- LEVEL 14: COLLECTIVE BARGAINING
('l14-q1', 14, 'Workers at a company want to form a trade union. The employer says only one union can exist in any industry.', 'What is the general principle on union formation under the ILRA?', 'Only one union per enterprise is ever permitted', 'Workers have the right to organise and form or join trade unions freely', 'Employers may prohibit union formation if they offer good conditions', 'Unions are only permitted in the public sector', 1, 'The ILRA protects the right to organise and join trade unions.', 'Industrial and Labour Relations Act, s.5', '', true),
('l14-q2', 14, 'A union and an employer negotiate a collective agreement that sets wages above the statutory minimum.', 'What is the legal status of a registered collective agreement?', 'A registered collective agreement is legally binding on parties covered by it', 'It has only the force of a gentleman''s agreement', 'It binds only union members who personally signed it', 'Collective agreements always lose to individual contracts', 0, 'Registered collective agreements are binding and operate within the statutory labour-relations framework.', 'Industrial and Labour Relations Act, Part VIII', '', true),
('l14-q3', 14, 'Workers go on an unprotected strike without following the statutory dispute resolution procedure.', 'What is the key legal consequence of an unprotected strike?', 'Strikers are immune from any action', 'The employer must negotiate immediately', 'Employees participating in an unprotected strike may face disciplinary action including dismissal', 'The Labour Commissioner must arbitrate within one day', 2, 'Unprotected industrial action carries serious disciplinary risk.', 'Industrial and Labour Relations Act, Part IX', '', true),
('l14-q4', 14, 'An employer refuses to recognise a union that has recruited more than half the eligible employees as members.', 'What obligation does the ILRA generally impose on the employer?', 'None, recognition is always voluntary', 'The employer must first seek court approval', 'The employer may delay recognition for two years', 'The employer must recognise the union once the statutory recognition threshold is met', 3, 'Recognition follows statutory thresholds and procedures rather than employer preference alone.', 'Industrial and Labour Relations Act, recognition provisions', '', true),
('l14-q5', 14, 'An employer dismisses an employee for participating in a lawful strike that followed the required dispute process.', 'What is the best legal answer?', 'All strikes are illegal in Zambia', 'Participation in a lawful strike is protected and should not be treated as breach of contract', 'Employers may dismiss any striking employee regardless of legality', 'Only union officials are protected during strikes', 1, 'Lawful strike participation receives statutory protection; unprotected strikes are different.', 'Industrial and Labour Relations Act, Part IX', 'Lusaka Engineering Company Ltd v Mukelabai [1992] ZMSC', true),
('l14-q6', 14, 'An employer deducts trade union subscriptions from employee wages without a statutory order and without agreement with eligible employees.', 'What is the correct position?', 'Individual agreement or a valid statutory order is required before deduction', 'The employer may deduct whenever a union exists', 'Only the union president''s oral request is required', 'Deductions are never permitted', 0, 'The ILRA distinguishes deduction authority from later remittance; deduction must rest on agreement or order.', 'Industrial and Labour Relations Act, ss.22 and 23', '', true),
('l14-q7', 14, 'An employee is dismissed after serving as a witness in a fellow employee''s labour dispute against the employer.', 'Is this dismissal lawful under the ILRA?', 'Yes, the employer may dismiss any employee for any reason', 'Only if the employer lost the case', 'No, victimisation for being a complainant or witness is prohibited', 'Only if the witness gave true testimony', 2, 'The ILRA protects employees from dismissal or disadvantage for participating as complainants or witnesses in proceedings.', 'Industrial and Labour Relations Act, s.5', '', true),
('l14-q8', 14, 'A collective agreement is approaching expiry, and the bargaining unit has not begun negotiations for a new one.', 'Under section 69, what should normally happen before expiry?', 'Nothing, agreements can expire without action', 'The Labour Commissioner must impose a new agreement', 'The employer may unilaterally extend the agreement', 'Negotiations for a new agreement should commence at least three months before expiry', 3, 'Section 69 requires timely bargaining before expiry.', 'Industrial and Labour Relations Act, s.69', '', true),
('l14-q9', 14, 'An employer wants to lock out employees over a collective dispute before conciliation has been attempted.', 'Can the employer lawfully proceed immediately?', 'Yes, employers have an absolute right to lock out', 'No, the collective dispute process, including conciliation steps, must be followed first', 'Yes, if 51 percent of employees support the lockout', 'Only if the lockout lasts less than seven days', 1, 'Strike and lockout action is regulated through the collective-dispute procedure.', 'Industrial and Labour Relations Act, Part IX', '', true),
('l14-q10', 14, 'A proposed trade union wants to register with only eighty members.', 'What is the minimum membership required for registration under section 9?', '50 members', '100 members', '150 members', '200 members', 1, 'Section 9 requires at least one hundred members for trade union registration.', 'Industrial and Labour Relations Act, s.9', '', true),
('l14-q11', 14, 'A union representative wants to attend union activities during working hours.', 'When may an employee participate in union activities during working hours?', 'Never; union activities must always be outside working hours', 'Only with employer consent or agreed arrangements', 'Anytime the employee chooses', 'Only if the employee is a union official', 1, 'Union activity during working hours depends on agreed arrangements or employer consent.', 'Industrial and Labour Relations Act, s.5(6)', 'Kelvin Lukonde v Mopani Copper Mines Plc', true),
('l14-q12', 14, 'A collective dispute has failed at conciliation and the employees want to strike.', 'What additional procedural safeguard is normally required before strike action?', 'A secret ballot or required employee vote under the statutory procedure', 'A criminal conviction of the employer', 'A court order in every strike', 'Approval by every customer of the business', 0, 'The statutory process requires worker approval through the required ballot/vote before protected industrial action.', 'Industrial and Labour Relations Act, ss.78 and 109', '', true),

-- LEVEL 15: DISPUTE RESOLUTION
('l15-q1', 15, 'An employee has been dismissed unfairly and wants to challenge the dismissal. Their legal adviser asks which forum has primary jurisdiction.', 'Which tribunal has primary jurisdiction over unfair dismissal disputes in Zambia?', 'The Magistrate''s Court', 'The Industrial Relations Division of the High Court', 'The Constitutional Court only', 'The Zambia Arbitration Centre', 1, 'The Industrial Relations Court/Division has primary jurisdiction in employment and industrial-relations disputes.', 'Industrial and Labour Relations Act, ss.85 and 85A', '', true),
('l15-q2', 15, 'A dispute arises and the parties want to try mediation before going to court.', 'What role does the Labour Commissioner play in employment dispute resolution?', 'The Labour Commissioner only enforces criminal sanctions', 'The Labour Commissioner provides conciliation and mediation services before disputes proceed to adjudication', 'The Labour Commissioner has no dispute-resolution function', 'The Labour Commissioner can issue binding arbitration awards without consent', 1, 'The Labour Commissioner is part of the statutory dispute-resolution pathway.', 'Employment Code Act, 2019, s.121; Industrial and Labour Relations Act', '', true),
('l15-q3', 15, 'A dismissed employee wins a case for wrongful dismissal. The court considers what remedy to award.', 'What remedies may be available in an appropriate dismissal case?', 'Reinstatement, re-engagement, re-employment, compensation, or another appropriate order', 'Only a written apology', 'Only criminal prosecution of the employer', 'The court can only award reinstatement', 0, 'The court has flexible remedial powers depending on the circumstances.', 'Industrial and Labour Relations Act, s.85A', 'Zulu & Another v Barclays Bank of Zambia Limited [2003] ZMSC 95', true),
('l15-q4', 15, 'An employer argues that a collective agreement interpretation dispute is outside the Industrial Relations Court.', 'What does section 85 say about the court''s jurisdiction?', 'The court has no jurisdiction over collective agreements', 'Only the Supreme Court can interpret collective agreements', 'The Labour Commissioner has exclusive jurisdiction', 'The court may interpret awards, collective agreements, and recognition agreements', 3, 'Section 85 includes interpretation of awards, collective agreements, and recognition agreements.', 'Industrial and Labour Relations Act, s.85', '', true),
('l15-q5', 15, 'An employee files a complaint in the Industrial Relations Court but the employer says strict civil evidence rules must apply.', 'What does section 85(5) provide?', 'Strict civil procedure and evidence rules always apply', 'The court is not bound by civil or criminal evidence rules; its main object is substantial justice', 'Only criminal evidence rules apply', 'The court must follow English evidence rules', 1, 'Section 85(5) gives the court flexibility to do substantial justice.', 'Industrial and Labour Relations Act, s.85(5)', 'Boart Longyear (Zambia) Ltd v Austin Makanya', true),
('l15-q6', 15, 'An employer wants to know if costs are automatically awarded to the winning party in the Industrial Relations Court.', 'When are costs generally awarded under the Industrial Relations Court Rules?', 'Costs are always awarded to the winner', 'Costs are never awarded', 'Costs are awarded only where justified by unreasonable delay, improper or vexatious steps, or unreasonable conduct', 'Costs are awarded only in dismissal cases', 2, 'Costs are not automatic and depend on conduct-based grounds.', 'Industrial Relations Court Rules, r.44', 'Amiran Ltd v Robert Bones [2010] ZMSC', true),
('l15-q7', 15, 'A constitutional question arises in an employment dispute before the Industrial Relations Division.', 'What must happen under the Constitution?', 'The Industrial Relations Division decides every constitutional question itself', 'The question is referred to the Constitutional Court where required', 'The employment case is automatically dismissed', 'The question is referred to the Labour Commissioner', 1, 'Constitutional questions may need referral to the Constitutional Court.', 'Constitution of Zambia, Art.127', 'Lubunda Ngala v Anti-Corruption Commission [2018] CCZ', true),
('l15-q8', 15, 'A worker brings a claim years after dismissal and the employer raises delay.', 'What practical issue should the court consider?', 'Delay is always irrelevant in employment matters', 'Whether limitation, laches, prejudice, or procedural rules affect the claim', 'Only whether the employee is unionised', 'Whether the employer approves late filing', 1, 'Delay can affect admissibility, prejudice, and remedies depending on the forum and governing rules.', 'Industrial and Labour Relations Act; Industrial Relations Court Rules', '', true),
('l15-q9', 15, 'A dispute concerns unpaid wages under an individual employment contract, not a union matter.', 'Can the Industrial Relations Court still hear the dispute?', 'No, it hears only collective union matters', 'Yes, section 85 extends jurisdiction to employment-contract disputes between employer and employee', 'Only if the trade union signs the pleadings', 'Only if the claim exceeds a High Court threshold', 1, 'Section 85 expressly includes individual employment-contract disputes.', 'Industrial and Labour Relations Act, s.85(3)-(4)', '', true),
('l15-q10', 15, 'A party ignores a binding order of the Industrial Relations Court.', 'What power does the court have?', 'No enforcement power at all', 'Only the Labour Commissioner can respond', 'Power to commit and punish for contempt where a person disobeys or refuses to be bound by an order', 'Only power to write a warning letter', 2, 'The court has contempt powers under section 85.', 'Industrial and Labour Relations Act, s.85(2)(d)', '', true),
('l15-q11', 15, 'An employee wins an unfair dismissal case but reinstatement is impractical because trust has broken down.', 'What can the court do instead?', 'Dismiss the successful claim', 'Order only a written apology', 'Make another appropriate remedy such as compensation, re-employment, re-engagement, or deeming retirement/retrenchment/redundancy where proper', 'Force the parties to sign a fresh contract for life', 2, 'The court has broad remedial discretion and does not have to order reinstatement in every successful case.', 'Industrial and Labour Relations Act, s.85A', '', true),
('l15-q12', 15, 'A dispute is settled through conciliation and written terms are prepared.', 'What is the practical purpose of recording the settlement?', 'To create a clear settlement record that can be submitted or relied on under the statutory dispute process', 'To erase all statutory rights forever', 'To convert the matter into a criminal case', 'To remove the court''s jurisdiction permanently', 0, 'Recorded settlements create certainty and support enforcement or approval within the dispute-resolution framework.', 'Industrial and Labour Relations Act, Part IX', '', true)
on conflict (id) do update set
  level = excluded.level,
  scenario = excluded.scenario,
  question = excluded.question,
  option_a = excluded.option_a,
  option_b = excluded.option_b,
  option_c = excluded.option_c,
  option_d = excluded.option_d,
  correct_index = excluded.correct_index,
  explanation = excluded.explanation,
  act_reference = excluded.act_reference,
  case_reference = excluded.case_reference,
  active = excluded.active;

update public.quiz_questions
set active = false
where id in (
  'l10-q13',
  'l10-q14',
  'l10-q15',
  'l11-q14',
  'l11-q15',
  'l12-q13',
  'l12-q14',
  'l13-q13',
  'l13-q14',
  'l13-q15',
  'l14-q13',
  'l14-q14'
);

-- Force fresh question selections for users who had already opened one of the
-- cleaned levels before this bank was updated.
update public.quiz_attempt_sessions
set expires_at = now() - interval '1 second'
where submitted_at is null
  and level in (1, 10, 11, 12, 13, 14, 15);
