-- Expand levels 10-15 so each level has a larger pool than the 12-question
-- attempt size. Questions are original wording based on statute/case concepts.

insert into public.quiz_questions (
  id,
  level,
  scenario,
  question,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_index,
  explanation,
  act_reference,
  case_reference,
  active
) values
-- LEVEL 10: WORKPLACE DISCIPLINE
('l10-q16', 10, 'An employee is accused of falsifying overtime records. The employer sends a dismissal letter before inviting the employee to respond.', 'What is the main procedural defect?', 'The employer should have decided the sanction after giving the employee a chance to answer the allegation', 'Overtime allegations can never justify dismissal', 'The employee must first be convicted in a criminal court', 'The employer needed approval from NAPSA', 0, 'A fair process requires the employer to hear the employee before deciding dismissal.', 'Employment Code Act, 2019, s.52(3)', 'Labour Law in Zambia, Ch.5', true),
('l10-q17', 10, 'A worker is charged with misconduct, but the charge letter does not say what rule was breached or what facts are relied on.', 'Why is this risky?', 'The employee may not have fair notice of the case they must answer', 'Charge letters are illegal in disciplinary cases', 'The employer must use only verbal charges', 'Only trade unions can issue charge letters', 0, 'Procedural fairness requires clear notice of the allegation so the employee can prepare a response.', 'Employment Code Act, 2019, s.52(3)', 'Labour Law in Zambia, Ch.5', true),
('l10-q18', 10, 'An employer has dismissed three employees for the same first-time minor offence, but only one was dismissed while the others received warnings.', 'Which fairness concern is strongest?', 'Inconsistent discipline may suggest unfair or discriminatory treatment', 'All employees must always receive the same salary', 'Warnings are unlawful under the Employment Code Act', 'The dismissed employee automatically becomes redundant', 0, 'Comparable misconduct should be treated consistently unless there is a defensible reason for different sanctions.', 'Employment Code Act, 2019, s.52', 'Labour Law in Zambia, Ch.5', true),
('l10-q19', 10, 'A disciplinary chairperson refuses to let the employee call a witness who was present during the incident.', 'What procedural principle is engaged?', 'The opportunity to present a defence and relevant evidence', 'The employer must call only management witnesses', 'Witness evidence is never allowed in workplace hearings', 'The Labour Commissioner must chair every hearing', 0, 'A fair disciplinary hearing should allow the employee a meaningful opportunity to respond, including relevant evidence where appropriate.', 'Employment Code Act, 2019, s.52(3)', 'Labour Law in Zambia, Ch.5', true),
('l10-q20', 10, 'A manager dismisses an employee for gross insubordination after the employee politely questioned an unsafe instruction.', 'What issue should HR examine first?', 'Whether the instruction was lawful and reasonable before treating refusal as misconduct', 'Whether the employee has worked more than five years', 'Whether the manager used capital letters in the warning', 'Whether the employee belongs to NAPSA', 0, 'Refusal to obey may be misconduct only where the instruction is lawful, reasonable, and within the employment relationship.', 'Employment Code Act, 2019, s.52(2)', 'Labour Law in Zambia, Ch.5', true),
('l10-q21', 10, 'An employee is dismissed for poor performance after one missed target, with no agreed performance standards.', 'What makes the dismissal vulnerable?', 'The employer may fail to prove a fair capacity reason without clear standards and an opportunity to improve', 'Poor performance can never justify dismissal', 'Targets are illegal in employment contracts', 'Only criminal misconduct can justify termination', 0, 'Capacity-based termination is stronger where expectations were clear, support was given, and dismissal was proportionate.', 'Employment Code Act, 2019, s.52(2)', 'Labour Law in Zambia, Ch.5', true),
('l10-q22', 10, 'An employee is summarily dismissed for alleged theft. The employer pays no wages already earned before dismissal.', 'What is the safest legal answer?', 'Earned wages are not automatically forfeited because of alleged misconduct', 'Summary dismissal always cancels all unpaid wages', 'Only union members can claim earned wages', 'The police decide whether wages are payable', 0, 'Misconduct does not automatically erase earned statutory wage entitlements.', 'Employment Code Act, 2019, ss.52 and 68', '', true),
('l10-q23', 10, 'An employer keeps an employee on indefinite suspension while an investigation is repeatedly delayed.', 'What is the strongest HR risk?', 'Unreasonable delay may make the suspension and process unfair', 'Suspension can never exceed one day', 'The employee must resign after seven days', 'Delay automatically proves the employee is guilty', 0, 'Suspension pending investigation should be managed fairly, consistently, and without unreasonable delay.', 'Employment Code Act, 2019, s.49', 'Labour Law in Zambia, Ch.5', true),
('l10-q24', 10, 'A disciplinary panel relies on anonymous allegations without putting the substance of those allegations to the employee.', 'What is the main fairness problem?', 'The employee cannot properly answer a case they do not know', 'Anonymous information is always perfect evidence', 'The employer must publish all employee names publicly', 'The matter becomes a redundancy issue', 0, 'The employee should know the substance of the case against them and have a fair chance to respond.', 'Employment Code Act, 2019, s.52(3)', 'Labour Law in Zambia, Ch.5', true),
('l10-q25', 10, 'An employee admits sleeping on duty once after working an unusually long shift approved by management.', 'What should the employer consider before dismissal?', 'Mitigation and whether dismissal is proportionate in the circumstances', 'Only the employee''s age', 'Whether the shift occurred in a leap year', 'Whether the customer complained online', 0, 'Admission of misconduct does not remove the need to consider seriousness, mitigation, consistency, and proportionality.', 'Employment Code Act, 2019, s.52', 'Labour Law in Zambia, Ch.5', true),
('l10-q26', 10, 'An employer wants to rely on operational requirements but the termination letter accuses the employee of dishonesty.', 'What is the problem with mixing these grounds?', 'The employer must identify and prove the real reason for termination', 'Operational requirements and misconduct are always identical', 'Dishonesty allegations require no evidence', 'The employee automatically receives promotion', 0, 'Section 52 requires a valid reason; unclear or shifting reasons create litigation risk.', 'Employment Code Act, 2019, s.52(2)', '', true),
('l10-q27', 10, 'A probationary employee is dismissed for misconduct without being told the allegation or allowed to respond.', 'Does probation remove all procedural fairness duties?', 'No, probation does not give an employer a licence to act unfairly', 'Yes, probationary employees have no statutory protection at all', 'Only permanent employees can be heard', 'The Labour Commissioner must approve every probation dismissal', 0, 'Probation affects assessment of suitability, but termination should still be grounded in fair and lawful reasons.', 'Employment Code Act, 2019, ss.27 and 52', 'Labour Law in Zambia, Ch.5', true),

-- LEVEL 11: WORKPLACE DISCRIMINATION
('l11-q16', 11, 'An employer rejects an applicant because she is pregnant, even though she meets all job requirements.', 'Which legal issue is most directly raised?', 'Pregnancy-related sex discrimination', 'A lawful preference for non-pregnant applicants', 'A redundancy selection issue only', 'A workers compensation claim', 0, 'Pregnancy-related disadvantage is closely connected to sex discrimination and maternity protection.', 'Employment Code Act, 2019, ss.5 and 43', '', true),
('l11-q17', 11, 'A workplace rule requires all employees to speak only one local language during breaks, disadvantaging workers from other regions.', 'What type of discrimination concern may arise?', 'Indirect discrimination based on language or social origin if unjustified', 'No concern because breaks are unpaid', 'Only criminal law applies', 'The rule is automatically valid because it applies to everyone', 0, 'A neutral language rule can still disadvantage protected groups if there is no objective justification.', 'Employment Code Act, 2019, s.5', 'Labour Law in Zambia, Ch.6', true),
('l11-q18', 11, 'A supervisor excludes an employee from training because the employee is close to retirement age.', 'Which protected ground is most likely engaged?', 'Age', 'Trade union membership only', 'Marital status only', 'Nationality only', 0, 'Age is a prohibited discrimination ground under the Employment Code Act.', 'Employment Code Act, 2019, s.5(2)(a)', '', true),
('l11-q19', 11, 'An employer requires all applicants to pass a height test that is not necessary for the job and excludes many women.', 'What is the best analysis?', 'The rule may be indirect sex discrimination unless objectively justified', 'The rule is always lawful because it is physical', 'Only men can challenge height requirements', 'Height tests are required by the Employment Code Act', 0, 'A physical requirement must be connected to genuine job needs and proportionate.', 'Employment Code Act, 2019, s.5', 'Labour Law in Zambia, Ch.6', true),
('l11-q20', 11, 'A manager gives better shifts only to employees from the manager''s tribe.', 'Which ground is most directly implicated?', 'Tribe or ethnic origin', 'Working hours only', 'Education level only', 'Probation status only', 0, 'Employment decisions based on tribe or ethnic origin raise direct discrimination concerns.', 'Employment Code Act, 2019, s.5(2)(a)', '', true),
('l11-q21', 11, 'An employer dismisses an employee after learning the employee joined a lawful trade union.', 'Which protection is most relevant?', 'Protection against anti-union victimisation and unfair termination', 'A rule against annual leave', 'A minimum-age rule', 'A pension contribution rule only', 0, 'Dismissal for union membership or lawful union activity may breach both labour-relations protections and fair-termination rules.', 'Employment Code Act, 2019, s.52(4); Industrial and Labour Relations Act, s.5', '', true),
('l11-q22', 11, 'A female employee is told she cannot work in a client-facing role because customers prefer men.', 'What is the best response?', 'Customer preference is not by itself a lawful justification for sex discrimination', 'Customer preference always overrides equality law', 'The employee must prove every customer objected', 'Only the client can be sued', 0, 'Business preference or stereotype is not the same as an inherent requirement of the job.', 'Employment Code Act, 2019, s.5', '', true),
('l11-q23', 11, 'An employer claims affirmative action allows it to exclude all men from promotion for the next ten years.', 'What is the key limit?', 'Affirmative action must be aimed at equality and remain proportionate to that aim', 'Affirmative action can never be used', 'Affirmative action only applies to wages', 'The Labour Commissioner must personally select each candidate', 0, 'Affirmative action is permitted to promote equality, but it should be connected to remedying disadvantage and used proportionately.', 'Employment Code Act, 2019, s.5(3)(a)', '', true),
('l11-q24', 11, 'An employee complains of sexual harassment and is transferred to a worse post while the accused manager remains in place.', 'What extra legal risk arises?', 'Victimisation for raising a discrimination complaint', 'Automatic redundancy', 'A pension-age dispute', 'A lawful promotion of the manager', 0, 'Retaliating against a person who raises a workplace-rights complaint can create an additional unfairness or discrimination issue.', 'Employment Code Act, 2019, ss.5 and 52(4)', '', true),
('l11-q25', 11, 'Two employees do work of equal value, but one is paid less because she is on a fixed-term contract.', 'What should HR assess?', 'Whether the pay difference is objectively justified and not discriminatory', 'Whether fixed-term workers are excluded from all wage protection', 'Whether the lower-paid worker signed a blank form', 'Whether the employee is under eighteen', 0, 'Equal-pay analysis asks whether work is of equal value and whether any difference has a lawful justification.', 'Employment Code Act, 2019, s.5(4)', '', true),
('l11-q26', 11, 'A job advert says only unmarried applicants will be considered for a payroll role.', 'Which issue is most likely raised?', 'Marital-status discrimination unless a lawful exception applies', 'A lawful universal recruitment rule', 'A redundancy consultation issue', 'A trade union recognition issue', 0, 'Marital status is a prohibited ground, and exclusion must be justified by a lawful exception if relied on.', 'Employment Code Act, 2019, s.5(2)(a)', '', true),

-- LEVEL 12: YOUNG PERSONS AND APPRENTICES
('l12-q15', 12, 'A parent gives written consent for a twelve-year-old to work full-time in a shop.', 'Does parental consent cure the age problem?', 'No, parental consent cannot override statutory minimum-age protections', 'Yes, parental consent is always enough', 'Only if wages are paid weekly', 'Only if the shop is family owned', 0, 'Minimum-age and child-labour protections are statutory safeguards that cannot be waived by private consent.', 'Employment Code Act, 2019, s.16 and Part V', '', true),
('l12-q16', 12, 'A fifteen-year-old is asked to carry heavy loads in a warehouse for long shifts.', 'What must the employer consider beyond the child''s age?', 'Whether the work is hazardous or harmful to health, safety, morals, schooling, or development', 'Only whether the child wants overtime', 'Only whether the employer has enough staff', 'Whether the child has a bank account', 0, 'Age eligibility does not permit hazardous or harmful work.', 'Employment Code Act, 2019, ss.80 and 83', '', true),
('l12-q17', 12, 'A young person works in an industrial undertaking without a certificate or apprenticeship contract.', 'Which statutory requirement is most directly engaged?', 'The requirement for an apprenticeship contract or authorised officer certificate', 'The right to paid public holidays only', 'The duty to join a trade union', 'The obligation to register with NHIMA only', 0, 'Section 84 regulates employment of young persons in industrial undertakings.', 'Employment Code Act, 2019, s.84', '', true),
('l12-q18', 12, 'An employer says record keeping for young workers is unnecessary because the workers know their ages.', 'What is the correct position?', 'Industrial-undertaking employers must keep the required register for young persons', 'No age records are ever required', 'Only schools can keep age records', 'Records are required only after an accident', 0, 'The Act requires specified records for young persons in industrial undertakings.', 'Employment Code Act, 2019, s.85', '', true),
('l12-q19', 12, 'A sixteen-year-old is asked to work overnight because the business is short-staffed.', 'What is the safest legal response?', 'Night work restrictions apply and exceptions must be checked carefully before scheduling', 'Night work is always allowed from age sixteen', 'Staff shortages automatically override the Act', 'Only female young persons are protected', 0, 'Section 86 restricts night work for young persons, subject only to specified exceptions.', 'Employment Code Act, 2019, s.86', '', true),
('l12-q20', 12, 'A business uses children to sell goods late at night in places where they may be exposed to exploitation.', 'Which concept is most relevant?', 'Work likely to harm the health, safety, or morals of children or young persons', 'Normal casual employment only', 'A collective-bargaining dispute only', 'A pension-registration issue', 0, 'Worst forms of labour include work likely to harm health, safety, or morals.', 'Employment Code Act, 2019, s.80', '', true),
('l12-q21', 12, 'A university student does vacation work for practical experience during the long break.', 'Which statement is most accurate about apprenticeship law?', 'The Apprenticeship Act may exclude university vacation work done to obtain experience', 'Every vacation placement is a formal apprenticeship', 'Vacation work is always illegal', 'The student must be under fifteen', 0, 'The Apprenticeship Act contains an exclusion for university students doing vacation work to obtain experience.', 'Apprenticeship Act, Cap. 275', '', true),
('l12-q22', 12, 'An employer asks whether a fifteen-year-old can sign an ordinary employment contract.', 'What is the correct starting point?', 'Fifteen is the general minimum contractual age, but child-labour restrictions still apply', 'Fifteen-year-olds can do any work without restriction', 'Only people aged twenty-one can sign employment contracts', 'Minimum age rules apply only to apprentices', 0, 'The minimum contractual age must be read together with restrictions on hazardous work, night work, and industrial undertakings.', 'Employment Code Act, 2019, s.16 and Part V', '', true),
('l12-q23', 12, 'A young worker is placed in a factory role involving dangerous machinery without training or safeguards.', 'Which legal concern is strongest?', 'Prohibited hazardous work and workplace safety risk', 'A maternity leave issue', 'A collective agreement interpretation issue', 'A retirement-age issue', 0, 'Dangerous machinery may create hazardous-work concerns for children and young persons.', 'Employment Code Act, 2019, ss.80 and 83', '', true),
('l12-q24', 12, 'An employer says children helping in a family business are never covered by labour protections.', 'What is the cautious answer?', 'Family context does not automatically remove statutory child-protection obligations', 'Family businesses are completely exempt from all labour laws', 'Only mining businesses are regulated', 'Children can waive all rights verbally', 0, 'Child-labour protections focus on the child and the nature of the work, not only the identity of the employer.', 'Employment Code Act, 2019, Part V', '', true),
('l12-q25', 12, 'A child is used to transport illicit substances for an adult-run business.', 'How is this treated under the worst-forms framework?', 'Use of children for illicit activities is included in the worst forms of labour', 'It is lawful if the child is paid', 'It is only a wage-record issue', 'It is lawful with parental consent', 0, 'The worst-forms definition includes use of children for illicit activities.', 'Employment Code Act, 2019, s.80', '', true),
('l12-q26', 12, 'An employer wants to rotate young persons between day and night shifts in a continuous factory operation.', 'What should be checked before implementing the rota?', 'Whether the statutory exception for continuous industrial operations genuinely applies', 'Whether the rota is convenient for payroll only', 'Whether the employee owns transport', 'Whether the worker has completed university', 0, 'Night-work exceptions for young persons are narrow and must be checked against the statutory conditions.', 'Employment Code Act, 2019, s.86', '', true),

-- LEVEL 13: SOCIAL SECURITY
('l13-q16', 13, 'An employer says NAPSA contributions are optional because employees prefer cash in hand.', 'What is the correct legal position?', 'Statutory social-security contributions cannot be waived by private preference', 'Employees can cancel NAPSA by oral agreement', 'NAPSA applies only if a union requests it', 'Cash payment removes every statutory duty', 0, 'Mandatory contribution duties are imposed by statute, not merely by employee preference.', 'National Pension Scheme Act', '', true),
('l13-q17', 13, 'An employer registers with NAPSA but omits temporary eligible employees from monthly returns.', 'What is the compliance risk?', 'Eligible employees must be included regardless of contract label', 'Temporary workers are always excluded', 'Only managers are covered by NAPSA', 'Registration alone is enough', 0, 'Coverage depends on statutory eligibility, not simply permanent status.', 'National Pension Scheme Act', '', true),
('l13-q18', 13, 'A worker suffers an occupational disease linked to workplace exposure rather than a single accident.', 'Which scheme is most relevant?', 'Workers compensation for employment-related injury or disease', 'Only the Apprenticeship Act', 'Only the Companies Act', 'A trade union registration claim', 0, 'Workers compensation covers work-related injuries and diseases within the statutory scheme.', 'Workers Compensation Act, No. 10 of 1999', '', true),
('l13-q19', 13, 'An employee receives sick-leave wages and later receives workers compensation for the same period.', 'What should payroll consider?', 'Sick-leave wages may need to be reduced by workers compensation received', 'The employee must return all salary forever', 'Workers compensation is never relevant to wages', 'Only NAPSA can approve sick leave', 0, 'The Employment Code Act coordinates sick leave wages with workers compensation.', 'Employment Code Act, 2019, s.38(4)', 'Workers Compensation Act', true),
('l13-q20', 13, 'An employer is below the turnover threshold for the Skills Development Levy.', 'What is the correct compliance response?', 'Check the statutory exemption instead of assuming all employers must pay', 'Pay double the levy automatically', 'Ignore all TEVETA correspondence', 'Register every employee as self-employed', 0, 'The Skills Development Levy has statutory exemptions, including low-turnover thresholds.', 'Skills Development Levy Act, No. 46 of 2016', '', true),
('l13-q21', 13, 'An employer deducts NHIMA contributions from pay but does not remit them.', 'What is the central problem?', 'Deduction without remittance breaches the contribution obligation', 'Deduction alone completes compliance', 'NHIMA applies only to retirees', 'Only the employee can remit employer contributions', 0, 'Contribution schemes require remittance to the statutory body, not merely deduction from payroll.', 'National Health Insurance Act, 2018', '', true),
('l13-q22', 13, 'A self-employed adult resident argues NHIMA cannot apply because there is no employer.', 'What is the best answer?', 'The National Health Insurance Act extends beyond ordinary employees to covered self-employed persons', 'NHIMA only applies to payroll employees', 'Self-employed persons are covered only if unionised', 'NHIMA was replaced by NAPSA', 0, 'The NHIMA framework includes self-employed covered persons.', 'National Health Insurance Act, 2018', '', true),
('l13-q23', 13, 'An employer treats workers compensation as a substitute for workplace safety obligations.', 'What is the compliance issue?', 'Compensation does not remove the duty to maintain safe systems of work', 'Compensation allows unsafe work if premiums are paid', 'Safety duties apply only to factories', 'Only employees can create safety policies', 0, 'Compensation schemes respond after injury; they do not replace prevention and safe-work duties.', 'Workers Compensation Act; Occupational Health and Safety Act', '', true),
('l13-q24', 13, 'An employee reaches early retirement age and asks whether ordinary retirement-age rules should be checked.', 'What is the best HR response?', 'Check normal, early, and late retirement rules under the pension statute and contract', 'Assume every employee must retire at fifty', 'Ignore the pension statute', 'Ask the employee to waive all pension rights', 0, 'Pension eligibility depends on the statutory retirement framework and any lawful employment terms.', 'National Pension Scheme Act, s.18', '', true),
('l13-q25', 13, 'A company delays registering new employees with social-security schemes until after probation.', 'What is the risk?', 'Probation does not automatically suspend statutory registration duties', 'Probation always excludes workers from social security', 'Only confirmed employees can ever be registered', 'Probation converts employees into contractors', 0, 'Statutory contribution duties should be assessed from the employment relationship and eligibility, not delayed merely by probation.', 'National Pension Scheme Act; National Health Insurance Act, 2018', '', true),
('l13-q26', 13, 'An employer classifies ordinary employees as independent contractors to avoid NAPSA and NHIMA contributions.', 'What should be examined?', 'The substance of the working relationship, not just the label used by the employer', 'Only the title printed on the payslip', 'Whether the worker has a personal phone', 'Whether the worker requested annual leave once', 0, 'Misclassification can defeat statutory protections and contribution obligations if substance shows employment.', 'Employment Code Act, 2019, s.3; National Pension Scheme Act', '', true),
('l13-q27', 13, 'A payroll officer asks why social-security records matter in employment compliance.', 'What is the strongest answer?', 'They evidence statutory registration, deductions, remittances, and benefit entitlement history', 'They are useful only for marketing', 'They replace employment contracts', 'They are optional once salaries are paid', 0, 'Accurate records support compliance and protect both employer and employee in benefit disputes.', 'National Pension Scheme Act; National Health Insurance Act, 2018', '', true),

-- LEVEL 14: COLLECTIVE BARGAINING
('l14-q15', 14, 'An employer offers wage increases only to employees who resign from the union.', 'What is the main legal problem?', 'Inducing employees to abandon union membership may amount to anti-union interference', 'Employers must pay union members less', 'Union membership cancels wage rights', 'Only NAPSA can approve wage increases', 0, 'Trade-union freedom includes protection against employer conduct that undermines lawful membership.', 'Industrial and Labour Relations Act, s.5', '', true),
('l14-q16', 14, 'A union wants recognition but has not shown it meets the statutory support threshold.', 'What should happen first?', 'Verify membership support against the recognition requirements', 'Recognition must be automatic for every union', 'The employer may ignore all unions forever', 'The Labour Commissioner must join the union', 0, 'Recognition depends on statutory thresholds and procedure.', 'Industrial and Labour Relations Act, recognition provisions', '', true),
('l14-q17', 14, 'A collective agreement gives benefits below the statutory minimum employment standard.', 'What is the legal effect?', 'The statutory minimum prevails over a less favourable collective term', 'Collective agreements can always reduce statutory rights', 'The employee must accept the lower benefit forever', 'The provision becomes a criminal conviction', 0, 'Collective bargaining can improve terms, but cannot lawfully undercut statutory minimum protections.', 'Employment Code Act, 2019; Industrial and Labour Relations Act', '', true),
('l14-q18', 14, 'A strike is called before the dispute has been reported and processed through statutory channels.', 'What is the key risk?', 'The strike may be unprotected, exposing participants to disciplinary consequences', 'Every strike is protected automatically', 'The employer must pay a strike bonus', 'Only customers can challenge the strike', 0, 'Protected industrial action depends on compliance with the statutory dispute process.', 'Industrial and Labour Relations Act, Part IX', '', true),
('l14-q19', 14, 'An employer refuses to deduct union dues despite a valid agreement or order requiring deductions.', 'What legal issue arises?', 'Failure to comply with deduction and remittance obligations', 'A maternity leave dispute', 'A pension age dispute only', 'An apprenticeship registration issue', 0, 'Where a valid agreement or order applies, the employer must handle union subscriptions as prescribed.', 'Industrial and Labour Relations Act, ss.22 and 23', '', true),
('l14-q20', 14, 'A union official asks to conduct union business during working hours without any agreed arrangement.', 'What is the correct starting point?', 'Working-hours union activity depends on consent or agreed arrangements', 'Union officials can leave work at any time without notice', 'Union business is always illegal', 'Only non-union workers need permission', 0, 'The ILRA protects union activity but regulates participation during working hours through consent or agreement.', 'Industrial and Labour Relations Act, s.5(6)', '', true),
('l14-q21', 14, 'A collective agreement is signed but never registered where registration is required.', 'What is the main concern?', 'The agreement may not enjoy the full statutory status of a registered collective agreement', 'It becomes a criminal statute', 'It automatically dissolves the union', 'It overrides the Constitution', 0, 'Registration is important to the legal status and enforceability of collective agreements.', 'Industrial and Labour Relations Act, Part VIII', '', true),
('l14-q22', 14, 'Employees take part in a lawful strike and the employer treats the absence as ordinary absenteeism.', 'What is the best legal response?', 'Protected strike participation should not be treated as ordinary breach of contract', 'All strike absence is desertion', 'Only managers may strike', 'The employer may cancel all earned wages', 0, 'Lawful industrial action receives statutory protection distinct from ordinary absenteeism.', 'Industrial and Labour Relations Act, Part IX', 'Lusaka Engineering Company Ltd v Mukelabai [1992] ZMSC', true),
('l14-q23', 14, 'A trade union refuses to represent some members because they criticised union leadership.', 'What governance issue may arise?', 'The union must act consistently with its statutory duties and rules toward members', 'Union leaders can ignore all members', 'Only employers owe labour-law duties', 'The criticism cancels membership automatically', 0, 'Union governance and member representation should follow the union rules and labour-relations framework.', 'Industrial and Labour Relations Act', '', true),
('l14-q24', 14, 'An employer changes collectively agreed conditions unilaterally during the life of the agreement.', 'What is the strongest legal risk?', 'Breach of the collective agreement and collective-bargaining framework', 'Automatic expiry of every employment contract', 'A criminal charge against every employee', 'A NAPSA refund claim', 0, 'Collectively agreed terms should not be changed unilaterally outside the agreement and statutory process.', 'Industrial and Labour Relations Act, Part VIII', '', true),
('l14-q25', 14, 'A union and employer reach deadlock over wages but skip conciliation to save time.', 'What is the problem?', 'Skipping conciliation can undermine protected strike or lockout action', 'Conciliation is forbidden in wage disputes', 'Deadlock automatically creates a new contract', 'Wage disputes must go only to the police', 0, 'The statutory collective-dispute process must be followed before protected industrial action.', 'Industrial and Labour Relations Act, Part IX', '', true),
('l14-q26', 14, 'An employee is disciplined for attending a union meeting outside working hours and away from the workplace.', 'What right is most directly implicated?', 'Freedom to participate in lawful trade-union activities', 'A minimum-age right', 'A workers compensation right', 'A right to avoid all workplace rules', 0, 'Lawful union participation is protected, especially outside working hours where workplace disruption is not at issue.', 'Industrial and Labour Relations Act, s.5', '', true),

-- LEVEL 15: DISPUTE RESOLUTION
('l15-q15', 15, 'An employee files an employment claim in the ordinary civil list despite the dispute being an industrial-relations matter.', 'What jurisdiction issue should be checked?', 'Whether the Industrial Relations Court or Division is the proper forum', 'Whether the claim belongs only to the police', 'Whether NAPSA can hear all dismissal cases', 'Whether the employer can choose any forum unilaterally', 0, 'Employment disputes may fall within the specialised jurisdiction of the Industrial Relations Court/Division.', 'Industrial and Labour Relations Act, ss.85 and 85A', '', true),
('l15-q16', 15, 'A complainant wins but asks for both reinstatement and compensation.', 'What should the court consider?', 'The appropriate remedy based on justice, practicality, and statutory powers', 'The court must always grant every requested remedy', 'The court can only write an apology', 'The employer chooses the remedy alone', 0, 'The court has broad remedial discretion but remedies must fit the case.', 'Industrial and Labour Relations Act, s.85A', '', true),
('l15-q17', 15, 'A party wants to appeal an Industrial Relations Court decision.', 'What should be checked first?', 'The applicable appeal route and whether the issue is law, fact, or mixed', 'Whether the losing party dislikes the result', 'Whether the employee has a union card', 'Whether the employer paid NHIMA', 0, 'Appeal rights and routes depend on the governing statute and the nature of the issue.', 'Industrial and Labour Relations Act', '', true),
('l15-q18', 15, 'A settlement is reached at conciliation, but one party later denies the terms.', 'Why are written settlement records important?', 'They provide evidence of agreed terms and support enforcement or further proceedings', 'They are only decorative', 'They replace all statutes', 'They make the dispute criminal', 0, 'Written settlement terms reduce uncertainty and help the parties or tribunal determine what was resolved.', 'Industrial and Labour Relations Act, dispute resolution provisions', '', true),
('l15-q19', 15, 'A court is asked to decide a constitutional issue arising inside an employment dispute.', 'What must be considered?', 'Whether the constitutional question must be referred to the Constitutional Court', 'Whether constitutional issues are banned in labour matters', 'Whether the employer can decide the Constitution privately', 'Whether NAPSA should write the judgment', 0, 'Constitutional questions may require referral under the Constitution.', 'Constitution of Zambia, Art.127', 'Lubunda Ngala v Anti-Corruption Commission [2018] CCZ', true),
('l15-q20', 15, 'A party repeatedly delays proceedings by failing to attend without good reason.', 'What consequence may follow?', 'The court may consider delay or unreasonable conduct when managing the case or costs', 'Delay is always rewarded', 'The case must restart every month', 'The other party loses automatically', 0, 'Unreasonable conduct can affect case management and costs in the Industrial Relations Court.', 'Industrial Relations Court Rules, r.44', '', true),
('l15-q21', 15, 'An employer ignores a reinstatement order after losing an unfair dismissal case.', 'What enforcement issue arises?', 'Disobedience of a court order may trigger contempt or enforcement proceedings', 'Court orders are optional in employment disputes', 'The employee must start probation again', 'Only the union can enforce the order', 0, 'Court orders are binding and may be enforced through the court''s powers.', 'Industrial and Labour Relations Act, s.85', '', true),
('l15-q22', 15, 'A litigant wants the Industrial Relations Court to apply technical evidence rules strictly to exclude relevant workplace documents.', 'What is the court''s guiding approach?', 'Substantial justice rather than strict technical rules of evidence', 'Only criminal evidence rules apply', 'No documents are allowed', 'Only oral evidence from managers is allowed', 0, 'The Industrial Relations Court is not bound by strict evidence rules and aims at substantial justice.', 'Industrial and Labour Relations Act, s.85(5)', 'Boart Longyear (Zambia) Ltd v Austin Makanya', true),
('l15-q23', 15, 'A former employee claims unpaid wages and dismissal remedies in the same dispute.', 'Can the court consider multiple employment remedies together?', 'Yes, if they arise from the employment dispute and are within jurisdiction', 'No, each kwacha requires a separate lawsuit', 'Only wage claims can be heard', 'Only dismissal claims can be heard', 0, 'Employment disputes often combine wage, dismissal, leave, and terminal-benefit issues.', 'Industrial and Labour Relations Act, ss.85 and 85A', '', true),
('l15-q24', 15, 'A party asks for costs simply because it won the case.', 'Is winning alone enough?', 'No, costs usually depend on conduct such as unreasonable delay or vexatious steps', 'Yes, costs are automatic in every case', 'Costs are never possible', 'Costs are decided by NAPSA', 0, 'Industrial-relations costs are not a routine winner-takes-all award; conduct matters.', 'Industrial Relations Court Rules, r.44', 'Amiran Ltd v Robert Bones [2010] ZMSC', true)
on conflict (id) do update set
  level = excluded.level,
  scenario = excluded.scenario,
  question = excluded.question,
  option_a = excluded.option_a,
  option_b = excluded.option_b,
  option_c = excluded.option_c,
  option_d = excluded.option_d,
  correct_index = excluded.correct_index,
  explanation = excluded.explanation,
  act_reference = excluded.act_reference,
  case_reference = excluded.case_reference,
  active = excluded.active;

-- Rotate the correct answer away from option A for a balanced answer key.
update public.quiz_questions
set
  option_a = option_b,
  option_b = option_a,
  correct_index = 1
where id in (
  'l10-q19', 'l10-q20', 'l10-q21',
  'l11-q19', 'l11-q20', 'l11-q21',
  'l12-q18', 'l12-q19', 'l12-q20',
  'l13-q19', 'l13-q20', 'l13-q21',
  'l14-q18', 'l14-q19', 'l14-q20',
  'l15-q18', 'l15-q19', 'l15-q20'
);

update public.quiz_questions
set
  option_a = option_b,
  option_b = option_c,
  option_c = option_a,
  correct_index = 2
where id in (
  'l10-q22', 'l10-q23', 'l10-q24',
  'l11-q22', 'l11-q23', 'l11-q24',
  'l12-q21', 'l12-q22', 'l12-q23',
  'l13-q22', 'l13-q23', 'l13-q24',
  'l14-q21', 'l14-q22', 'l14-q23',
  'l15-q21', 'l15-q22'
);

update public.quiz_questions
set
  option_a = option_b,
  option_b = option_c,
  option_c = option_d,
  option_d = option_a,
  correct_index = 3
where id in (
  'l10-q25', 'l10-q26', 'l10-q27',
  'l11-q25', 'l11-q26',
  'l12-q24', 'l12-q25', 'l12-q26',
  'l13-q25', 'l13-q26', 'l13-q27',
  'l14-q24', 'l14-q25', 'l14-q26',
  'l15-q23', 'l15-q24'
);

update public.quiz_attempt_sessions
set expires_at = now() - interval '1 second'
where submitted_at is null
  and level in (10, 11, 12, 13, 14, 15);
