insert into public.document_products (
  id,
  title,
  category,
  price,
  currency,
  summary,
  best_for,
  format,
  delivery,
  includes,
  display_order,
  is_active
) values (
  'hr-officer-salary-report-2026',
  'Mid-Year 2026 HR Officer Salary Report',
  'Salary Reports',
  85.00,
  'ZMW',
  'A clear, data-led snapshot of what Zambia HR officers earn, value and need in 2026.',
  'HR officers, HR managers, employers, recruiters and compensation decision-makers.',
  'Online image-page reader',
  'Available in your BMAS Library after payment confirmation',
  array['29-page salary report', 'Compensation insights', 'Compliance, benefits and career moves snapshot'],
  10,
  true
) on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  price = excluded.price,
  currency = excluded.currency,
  summary = excluded.summary,
  best_for = excluded.best_for,
  format = excluded.format,
  delivery = excluded.delivery,
  includes = excluded.includes,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = now();
