-- ============================================================
-- BMAS Employment Law Quiz — Supabase Migration
-- Run this in the Supabase SQL editor
-- ============================================================

-- ── 1. Questions table ────────────────────────────────────────
create table if not exists public.quiz_questions (
  id              text        primary key,          -- e.g. 'l1-q1'
  level           smallint    not null,
  scenario        text        not null,
  question        text        not null,
  option_a        text        not null,
  option_b        text        not null,
  option_c        text        not null,
  option_d        text        not null,
  correct_index   smallint    not null,             -- 0-3, NEVER sent to browser
  explanation     text        not null default '',
  act_reference   text        not null default '',
  case_reference  text        not null default '',
  active          boolean     not null default true,
  created_at      timestamptz not null default now()
);

-- Only service-role can read correct_index.
-- Anon / authenticated users get everything EXCEPT correct_index via an RLS-safe view.
alter table public.quiz_questions enable row level security;

-- Service role needs explicit permission to read questions for the API
create policy "Service role can read all questions"
  on public.quiz_questions
  for select
  using (auth.role() = 'service_role');

-- No direct select allowed on the table for anon/authenticated —
-- they go through the secure view or the API function instead.
create policy "No direct browser access to questions table"
  on public.quiz_questions
  for select
  using (false);

-- ── 2. Safe view — options only, no correct_index ─────────────
create or replace view public.quiz_questions_safe as
  select
    id,
    level,
    scenario,
    question,
    option_a,
    option_b,
    option_c,
    option_d,
    active
  from public.quiz_questions;

-- Grant read on the safe view to anon and authenticated roles
grant select on public.quiz_questions_safe to anon, authenticated;

-- ── 3. Server-side score function (security definer) ─────────
-- Called by /api/quiz-submit — runs as postgres so it can read correct_index.
-- Returns per-question feedback WITHOUT leaking the correct index raw value
-- (it constructs a safe result object instead).
create or replace function public.score_quiz_attempt(
  p_question_ids  text[],
  p_answers       smallint[]   -- same order as p_question_ids, null = unanswered
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result      jsonb := '[]'::jsonb;
  v_correct     int   := 0;
  v_total       int   := array_length(p_question_ids, 1);
  v_question    record;
  v_answer      smallint;
  v_is_correct  boolean;
  i             int;
begin
  for i in 1 .. v_total loop
    select * into v_question
    from quiz_questions
    where id = p_question_ids[i];

    if not found then
      raise exception 'Question not found: %', p_question_ids[i];
    end if;

    v_answer     := p_answers[i];
    v_is_correct := (v_answer is not null and v_answer = v_question.correct_index);

    if v_is_correct then
      v_correct := v_correct + 1;
    end if;

    v_result := v_result || jsonb_build_object(
      'id',             v_question.id,
      'is_correct',     v_is_correct,
      'correct_index',  v_question.correct_index,   -- safe to return post-submission
      'explanation',    v_question.explanation,
      'act_reference',  v_question.act_reference,
      'case_reference', v_question.case_reference,
      'correct_option', case v_question.correct_index
                          when 0 then v_question.option_a
                          when 1 then v_question.option_b
                          when 2 then v_question.option_c
                          when 3 then v_question.option_d
                        end
    );
  end loop;

  return jsonb_build_object(
    'correct_count',    v_correct,
    'total_questions',  v_total,
    'raw_score',        case when v_total > 0 then round((v_correct::numeric / v_total), 4) else 0 end,
    'passed',           case when v_total > 0 then (v_correct::numeric / v_total) >= 0.5 else false end,
    'details',          v_result
  );
end;
$$;

-- Grant execute to authenticated users (called server-side via service role anyway,
-- but this keeps things clean)
grant execute on function public.score_quiz_attempt(text[], smallint[]) to service_role;

-- ── 4. quiz_profiles (if not already created) ────────────────
create table if not exists public.quiz_profiles (
  user_id        uuid        primary key references auth.users(id) on delete cascade,
  alias          text        not null,
  current_level  smallint    not null default 1,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

alter table public.quiz_profiles enable row level security;

create policy "Users can read and write their own profile"
  on public.quiz_profiles
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ── 5. quiz_attempts (if not already created) ────────────────
create table if not exists public.quiz_attempts (
  id                uuid        primary key default gen_random_uuid(),
  user_id           uuid        not null references auth.users(id) on delete cascade,
  display_alias     text        not null,
  level             smallint    not null,
  month_key         date        not null,
  score             numeric(6,4) not null,
  passed            boolean     not null,
  correct_count     smallint    not null,
  total_questions   smallint    not null,
  duration_seconds  int         not null default 0,
  submitted_at      timestamptz not null default now(),
  unique (user_id, level, month_key)
);

alter table public.quiz_attempts enable row level security;

create policy "Service role can read and write attempts"
  on public.quiz_attempts
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create policy "Users can insert their own attempts"
  on public.quiz_attempts
  for insert
  with check (auth.uid() = user_id);

create policy "Users can read their own attempts"
  on public.quiz_attempts
  for select
  using (auth.uid() = user_id);

create policy "Anyone can read leaderboard data"
  on public.quiz_attempts
  for select
  using (true);

-- ── 6. Leaderboard monthly snapshot (if not already created) ──
create table if not exists public.leaderboard_monthly_snapshot (
  id            uuid        primary key default gen_random_uuid(),
  month_key     date        not null,
  rank          smallint    not null,
  display_alias text        not null,
  score         numeric(6,4) not null,
  level         smallint    not null,
  created_at    timestamptz not null default now()
);

alter table public.leaderboard_monthly_snapshot enable row level security;

create policy "Anyone can read hall of fame"
  on public.leaderboard_monthly_snapshot
  for select
  using (true);

-- ── 7. Seed all 112 questions ─────────────────────────────────
-- correct_index: 0=A, 1=B, 2=C, 3=D

insert into public.quiz_questions (id, level, scenario, question, option_a, option_b, option_c, option_d, correct_index, explanation, act_reference, case_reference) values

-- LEVEL 1
('l1-q1',1,'A member of the Zambia Police Service claims ordinary coverage under the Employment Code Act, 2019.','What is the best starting legal answer?','The Act automatically applies to every worker in Zambia without exception','The Act does not apply to members of the Zambia Police Service','The Act applies only if the person has worked for twelve months','The Act applies only if the Labour Commissioner agrees in writing',1,'Section 2 excludes members of the Zambia Police Service from the Act.','Employment Code Act, 2019, s.2(1)(b)',''),
('l1-q2',1,'A company pays one woman less than a man doing work of equal value even though they perform the same duties at the same level.','Which section is most directly engaged by this scenario?','Section 5 on non-discrimination and equal wages for work of equal value','Section 27 on probation','Section 55 on redundancy','Section 73 on gratuity',0,'Section 5 prohibits discrimination and specifically requires equal wages for work of equal value.','Employment Code Act, 2019, s.5(1)–(4)',''),
('l1-q3',1,'An employer keeps re-engaging the same worker on temporary terms for eight months to do a core, regular job with fixed weekly hours and no valid temporary reason.','What is the strongest legal concern?','The worker automatically becomes a director of the company','The arrangement may amount to prohibited casualisation','The employer has created a lawful apprenticeship','The worker loses all rights because the contract was temporary',1,'Using temporary or fixed arrangements without a permissible reason for work that is permanent in nature may amount to prohibited casualisation.','Employment Code Act, 2019, s.7',''),
('l1-q4',1,'A person is compelled to work under threats and cannot freely leave the arrangement.','Which core statutory prohibition is most directly raised?','Only a wage record breach','A prohibition against forced labour','Only a minor overtime issue','A probation extension issue',1,'The Act prohibits forced labour and makes contravention an offence.','Employment Code Act, 2019, s.8',''),
('l1-q5',1,'An employer issues a contract lasting for two years with a fixed end date agreed by both parties.','How does the Act most accurately classify that contract?','A permanent contract only','A long-term contract','A casual engagement','A public holiday arrangement',1,'A contract with a fixed end date of more than one year is a long-term contract under the Act.','Employment Code Act, 2019, s.21',''),
('l1-q6',1,'An employer engages a worker for a specific task expected to last three weeks.','What type of contract is this under the Act?','A permanent contract','A short-term contract','A long-term contract','A casual contract only',1,'A contract for a specific task or period not exceeding one year is a short-term contract.','Employment Code Act, 2019, s.20',''),
('l1-q7',1,'An employer says it can dictate any working terms because Zambia has no minimum employment standards.','Which statement best corrects that view?','The employer is correct — working terms are purely private','The Employment Code Act sets minimum standards that apply regardless of contract','Only the Constitution governs employment terms','Minimum standards apply only in the mining sector',1,'The Employment Code Act sets statutory minimums that override contrary contractual terms.','Employment Code Act, 2019, s.3',''),
('l1-q8',1,'An employer wants to engage someone for agricultural harvesting work that occurs only during a specific season each year.','Which contract type best fits that arrangement under the Act?','A permanent contract','A seasonal employment contract','A long-term contract','A casual contract',1,'Work that recurs in a particular season of the year qualifies as seasonal employment under the Act.','Employment Code Act, 2019, s.22',''),
('l1-q9',1,'A worker with no fixed end date and no specific task limitation has worked for three years under the same employer.','What employment type does the Act recognise here?','Short-term employment','Permanent employment','Seasonal employment','Apprenticeship only',1,'Employment with no fixed term or specific task limitation is permanent employment.','Employment Code Act, 2019, s.23',''),

-- LEVEL 2
('l2-q1',2,'An employer dismisses a worker verbally and without any hearing or investigation, claiming the dismissal is lawful because the worker was rude to a client once.','What is the strongest legal problem with this dismissal?','Verbal dismissal is always valid','The employer failed to follow fair dismissal procedure including hearing','Rudeness is never a disciplinary matter','The employer needed only a letter of apology',1,'The Act requires a fair hearing and proper disciplinary procedure before dismissal. In Redrilza v Nkazi, the Supreme Court found the dismissal wrongful and ordered compensation, holding that dismissal and termination must not be conflated and that procedural fairness cannot be bypassed.','Employment Code Act, 2019, s.52(3)','Redrilza v Nkazi [2011] ZMSC 7'),
('l2-q2',2,'An employer terminates a permanent employee on one day''s verbal notice citing operational reasons.','What minimum notice period does the Act require for a permanent employee?','One day is always sufficient','The notice period set in the contract or at least the statutory minimum','No notice is required for operational terminations','Three years of prior warning are needed',1,'Termination requires at least the contractual or statutory notice period; same-day verbal notice fails the standard.','Employment Code Act, 2019, s.52 and s.53',''),
('l2-q3',2,'An employee resigns and asks for a certificate of service. The employer refuses, saying the employee left voluntarily.','What does the Act say about this?','Certificates are only for dismissed employees','The employer must provide a certificate of service on any termination of employment','The employee must apply to court first','The employer can charge a fee for the certificate',1,'On any termination of employment — including resignation — the employer must provide a certificate of service.','Employment Code Act, 2019, s.59(1)',''),
('l2-q4',2,'An employer dismisses an employee for gross misconduct without notice.','Under the Act, when is summary dismissal (no notice) permissible?','Whenever the employer prefers speed','Only for gross misconduct after a fair hearing','Whenever the employee earns above minimum wage','Only if the employee agrees in advance',1,'Summary dismissal without notice is only lawful for gross misconduct, and a fair hearing is still required.','Employment Code Act, 2019, s.52(4)',''),
('l2-q5',2,'An employer uses the word "termination" in a letter, but the facts show the move was disciplinary and based on alleged misconduct.','Which case most usefully distinguishes dismissal from termination?','Redrilza v Nkazi','Only criminal-law precedent matters','No case law distinguishes the two terms','Section 95 alone answers the issue',0,'Redrilza v Nkazi is the leading Zambian Supreme Court authority on this distinction. The court held they are not interchangeable: dismissal is disciplinary and requires a fair process. The employee''s wrongful dismissal claim succeeded and damages were awarded.','Employment Code Act, 2019, s.52','Redrilza v Nkazi [2011] ZMSC 7'),
('l2-q6',2,'An employer serves a notice of termination while the employee is on annual leave.','What does section 53 say about that?','Notice can validly run during leave in all cases','The employer may only do so for executives','The employer must not give notice during a period of leave or allow it to run concurrently with leave','The employee must accept the notice because leave is a privilege only',2,'The Act bars an employer from giving notice during leave or allowing the notice period to run concurrently with leave.','Employment Code Act, 2019, s.53(3)',''),
('l2-q7',2,'A fixed-duration contract ends early, and the employee asks what statutory severance formula applies.','What is the key statutory answer?','No severance can ever arise on a fixed-duration contract','Severance is a gratuity at not less than 25 percent of basic pay earned during the contract period','Severance must always equal twelve months gross pay','Only expatriates qualify',1,'In Sandie Mkandawire v Trinity University, the court awarded gratuity at 25% of basic pay earned from contract start to the termination date, unpaid wages, and accrued leave pay, after finding the dismissal wrongful for lack of hearing.','Employment Code Act, 2019, s.54(1)(c)','Sandie Mkandawire v Trinity University [2025] ZMHC 55'),
('l2-q8',2,'An employer withholds statutory terminal benefits as a way of punishing an employee after separation.','Which answer is strongest?','The employer may withhold statutory benefits as leverage','Statutory benefits cannot be withheld as punishment contrary to the Act','Benefits can be withheld automatically whenever there is a dispute','Only oral instructions are needed to stop payment',1,'In Harrison Phiri v Akaal Engineering Limited, the court found the withholding unlawful and ordered full payment of all outstanding statutory dues, rejecting the argument that a dispute justified withholding.','Employment Code Act, 2019, ss.52–54','Harrison Phiri v Akaal Engineering Limited [2024] ZMHC 258'),
('l2-q9',2,'An employer claims an employee resigned, but the employee insists the employer actually dismissed him.','What is the best legal approach?','Always accept the employer''s label without examining facts','Examine the facts closely because resignation versus dismissal is a real legal distinction','Treat both concepts as identical','Ignore the notice issue entirely',1,'In Esau Shamalambo v China Zambia Friendship Farm Ltd, the court looked past the employer''s label, found the employee had been dismissed, and awarded notice pay plus all accrued terminal entitlements.','Employment Code Act, 2019, ss.52 and 53','Esau Shamalambo v China Zambia Friendship Farm Ltd [2024] ZMHC 230'),

-- LEVEL 3
('l3-q1',3,'An employer plans to declare several employees redundant next week because business has slowed down.','Which procedural requirement is missing on these facts?','The employer only needs to inform employees on the last day of duty','The employer must notify an authorised officer at least sixty days before effecting the redundancy','The employer must convert every employee to an expatriate contract','The employer must wait until the end of the decade',1,'In Oliver Zimba and Ors v Kay Two Zambia Limited, the court found the sixty-day notice obligation had been breached and ordered the employer to continue paying full wages until every redundancy package was settled.','Employment Code Act, 2019, s.55(2)','Oliver Zimba and Ors v Kay Two Zambia Limited [2023] ZMHC 42'),
('l3-q2',3,'A redundancy has already taken effect, but the employer says the package cannot be paid on the employee''s last day of duty.','What does section 55 require unless a lawful exemption applies?','The employer may stop paying the employee immediately','The employee must work for free until the package is ready','The employer must continue paying full wages until the redundancy package is paid','The employee loses the right to redundancy payment',2,'In Oliver Zimba and Ors v Kay Two Zambia Limited, this is exactly what the court ordered — the company was directed to keep paying full salaries to all affected employees until every outstanding package was fully settled.','Employment Code Act, 2019, s.55(3)(b)','Oliver Zimba and Ors v Kay Two Zambia Limited [2023] ZMHC 42'),
('l3-q3',3,'An employer wants to transfer an employee to another employer without the employee''s written consent.','Which answer best fits the Act?','Transfer is allowed if the current employer prefers speed','Transfer requires the written consent of the employee and other statutory steps','Only verbal consent from a supervisor is enough','Transfer is automatic once announced on a notice board',1,'An employer must not transfer rights under a contract of employment without the employee''s written consent, notice to the representative, and endorsement by an authorised officer.','Employment Code Act, 2019, s.28(1)',''),
('l3-q4',3,'Within nine months after a redundancy, the employer wants to refill the same kind of vacancy.','What does the Act require before considering new applicants?','The employer may ignore the former employee entirely','The employer must first offer the vacancy to the employee previously declared redundant','The employer must only advertise internationally','The employer must seek parliamentary approval',1,'If within nine months of redundancy the employer wishes to fill the vacancy, the former redundant employee must be offered the contract first.','Employment Code Act, 2019, s.57',''),
('l3-q5',3,'An employee refuses to be transferred to another employer under a proposed transfer arrangement.','What is the statutory consequence of that refusal?','The employee is jailed for breach of contract','The contract terminates and the employee is entitled to severance pay','The employee must accept a pay cut instead','The employee loses all accrued benefits automatically',1,'If an employee refuses transfer under section 28, the contract terminates and the employee is entitled to severance pay.','Employment Code Act, 2019, s.29',''),
('l3-q6',3,'A pregnant employee is selected for adverse treatment because she is pregnant and has taken maternity-related leave.','Which statement best reflects the Code?','Pregnancy is a valid reason for termination if the employer is busy','The employer may impose any disadvantage because maternity leave is optional','The employer must not terminate or disadvantage the employee because of pregnancy or maternity leave','The employee must resign before seeking maternity protection',2,'The Act protects employees from termination, penalty, or disadvantage because of pregnancy or maternity leave.','Employment Code Act, 2019, s.43',''),
('l3-q7',3,'An employer says a worker is redundant but cannot show any real reduction in work or operational reorganisation.','What is the strongest legal risk for the employer?','No risk exists once the word "redundancy" is used','A court may find the stated operational basis unproven or unlawful','Redundancy can never be challenged in court','The employee must accept the label without question',1,'In Jimmy Mulusa v First National Bank Zambia Limited, the court found FNB had not substantiated its claimed operational requirements and awarded compensation for wrongful termination.','Employment Code Act, 2019, ss.52(2) and 55','Jimmy Mulusa v First National Bank Zambia Limited [2024] ZMHC 184'),
('l3-q8',3,'An employer terminates several employees for alleged misconduct but never gives any of them a fair hearing.','Which legal idea is most important to test in that scenario?','Procedural fairness and the opportunity to be heard remain central','A hearing is optional whenever suspicion exists','Misconduct allegations erase all procedural rights','Only the police may decide workplace fairness',0,'In Protea Hotels Zambia v Longa William Mulikelela, the Court of Appeal dismissed the employer''s appeal and upheld the damages award, confirming that skipping the hearing made the dismissal unlawful regardless of the evidence.','Employment Code Act, 2019, s.52(3)','Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116'),
('l3-q9',3,'An undertaking has no HIV and AIDS policy, no grievance procedure, and no code of conduct.','What is the strongest legal issue?','These policies are optional if the employer is small','The employer must ensure that employment policies, procedures, and codes exist in the undertaking','Only trade unions may keep such documents','Such policies are required only after a lawsuit is filed',1,'The Act requires an employer to ensure that key employment policies — including an HIV and AIDS policy, grievance procedure, and code of conduct — exist.','Employment Code Act, 2019, s.95',''),

-- LEVEL 4
('l4-q1',4,'A labour law lecturer says Zambia''s earliest colonial employment laws were rooted in a UK policy of allowing bargaining to determine wages.','What was that UK policy called?','Absolutism','Voluntarism','Interventionism','Collectivism',1,'The UK pursued a policy of voluntarism under which individual and collective bargaining largely determined wages and conditions of service.','Labour Law in Zambia: An Introduction, Ch.1',''),
('l4-q2',4,'A student asks why voluntarism translated poorly into Northern Rhodesia''s early labour environment.','Which factor best explains why voluntarism did not work well in colonial Northern Rhodesia?','Workers were too wealthy to care about wages','Workers were vulnerable, illiterate, and driven by poll-tax policies; unions were unknown initially','The UK government imposed high wages directly','Northern Rhodesia was already fully industrialised',1,'Colonial Northern Rhodesia lacked the industrial base and strong unions that made voluntarism viable in the UK; workers were instead driven by poll-tax policies.','Labour Law in Zambia: An Introduction, Ch.1',''),
('l4-q3',4,'Someone asks which statute consolidated the Employment Act, Employment of Young Persons and Children Act, and the Minimum Wages and Conditions of Employment Act.','Which statute performs that consolidation?','The Industrial and Labour Relations Act','The Employment Code Act, 2019','The Workers Compensation Act','The Gender Equality Act',1,'The Employment Code Act, No 3 of 2019, consolidated several previously fragmented employment statutes into one Act.','Employment Code Act, 2019 preamble; Labour Law in Zambia, Ch.1',''),
('l4-q4',4,'An employer argues its employment contract clause should prevail over the Employment Code Act minimum because both parties agreed freely.','Which constitutional principle overrides that argument?','Parliamentary sovereignty only','Constitutional supremacy — the Constitution is the supreme law and any inconsistent statute or practice is void','The principle of freedom of contract overrides statutes','Only courts may override contracts',1,'Zambia''s Constitution is the supreme law; legislation must conform to it, and contractual terms cannot undercut statutory minimums.','Constitution of Zambia; Labour Law in Zambia, Ch.1',''),
('l4-q5',4,'A government official asks which body sets international labour standards that Zambia is expected to observe.','Which body primarily sets those international labour standards?','The World Trade Organisation','The International Labour Organisation (ILO)','The African Development Bank','The United Nations Security Council',1,'The ILO sets international labour standards through conventions and recommendations that member states, including Zambia, are expected to follow.','Labour Law in Zambia: An Introduction, Ch.1',''),
('l4-q6',4,'A researcher notes that Zambia''s ILRA 1971 made two umbrella organisations the compulsory representatives of unions and employers respectively.','What are those two bodies?','NAPSA and NHIMA','ZCTU and ZFE','ZICA and ZABS','PACRA and ZRA',1,'The ILRA 1971 designated the Zambia Congress of Trade Unions (ZCTU) and the Zambia Federation of Employers (ZFE) as the umbrella bodies.','Labour Law in Zambia: An Introduction, Ch.1',''),

-- LEVEL 5
('l5-q1',5,'An employer argues that an oral contract of employment it made is not enforceable because it was never put in writing.','Is an oral employment contract valid under the Act?','No — all employment contracts must be in writing to be valid','Yes — oral contracts are recognised, though written terms provide more protection','Only for casual workers','Only if witnessed by a labour officer',1,'The Act recognises oral contracts, though written contracts offer clearer evidence of terms.','Employment Code Act, 2019, s.16; Labour Law in Zambia, Ch.2',''),
('l5-q2',5,'An employer places a new hire on probation for nine months.','What is the maximum probation period permitted under the Act?','Six months','Three months, extendable once','One year','The Act does not limit probation periods',0,'The Act limits probation to a maximum of six months.','Employment Code Act, 2019, s.27(1)',''),
('l5-q3',5,'During probation a worker is dismissed without being told the reason.','Is an employer required to give reasons for dismissal during probation?','No — probation is a free trial period with no rights','Yes — even during probation, dismissal must follow a fair process with reasons','Only if the worker demands reasons in writing first','Only after three months of probation',1,'Even during probation employees retain rights to a fair dismissal procedure.','Employment Code Act, 2019, s.27(6)',''),
('l5-q4',5,'An employer changes key salary terms unilaterally without consulting the employee.','What is the legal risk of unilateral variation of contract terms?','None — employers can change terms whenever they wish','The employee may treat the unilateral change as a breach and claim constructive dismissal','The change is valid if posted on a notice board for one week','Only changes to working hours can be challenged',1,'Unilateral variation of material contract terms without consent may amount to a breach, potentially grounding a constructive-dismissal claim.','Employment Code Act, 2019, s.25; Labour Law in Zambia, Ch.2',''),
('l5-q5',5,'A contract includes an express term but also a conflicting implied duty of mutual trust and respect.','Which type of term generally prevails when they conflict in Zambian employment law?','The implied term always prevails','Express terms prevail, but implied statutory duties cannot be excluded','Neither term matters once the contract is signed','Only collective agreement terms count',1,'Express terms normally govern, but implied terms arising from statute or fundamental common-law duties cannot be contractually excluded.','Labour Law in Zambia: An Introduction, Ch.2',''),
('l5-q6',5,'An employer wants to send an employee on secondment to a government department for eight months.','What must an employer do before seconding an employee?','Nothing — secondment is informal','Obtain the employee''s consent and ensure the arrangement is documented','Inform NAPSA only','Wait for parliamentary approval',1,'Secondment requires the employee''s consent and should be documented to protect both parties'' rights.','Employment Code Act, 2019, s.28; Labour Law in Zambia, Ch.2',''),

-- LEVEL 6
('l6-q1',6,'An employee sets up a competing business while still employed and uses confidential client lists from the employer.','Which two common-law duties are most directly breached?','Duty to obey and duty to indemnify','Duty of confidentiality and duty to avoid conflicts of interest','Duty to adapt and duty to provide work','Duty of skill and duty to pay wages',1,'Employees owe duties of confidentiality and must avoid conflicts of interest; breaching both by competing while employed and using confidential data is a serious violation.','Labour Law in Zambia: An Introduction, Ch.3',''),
('l6-q2',6,'An employer''s employee negligently injures a customer while performing duties in the course of employment.','What legal doctrine makes the employer potentially liable to the customer?','Subrogation','Vicarious liability','Strict liability','Contributory negligence only',1,'Vicarious liability makes an employer responsible for wrongs committed by an employee acting in the course of employment.','Labour Law in Zambia: An Introduction, Ch.3',''),
('l6-q3',6,'An employer refuses to provide any work to an employee who is ready, willing, and able to perform duties.','Which employer common-law duty does this breach?','Duty to pay wages only','Duty to provide work','Duty to indemnify the employee','Duty of confidentiality',1,'An employer has a common-law duty to provide work, particularly where the employee''s earnings depend on actually working or where skill maintenance matters.','Labour Law in Zambia: An Introduction, Ch.3',''),
('l6-q4',6,'A departing employee is subject to a restraint-of-trade clause preventing work in the same industry for two years across all of Zambia.','When will Zambian courts enforce a restraint-of-trade clause?','Always, if the employer paid good wages','Only if it is reasonable in scope, area, and duration, and protects a legitimate interest','Never — such clauses are always void','Only for expatriate employees',1,'Courts enforce restraint clauses only when they are reasonable in scope, geographic reach, and duration, and when they protect a legitimate proprietary interest.','Labour Law in Zambia: An Introduction, Ch.3',''),
('l6-q5',6,'An employer provides a false or misleading reference about a departing employee that causes the employee to lose a job offer.','What legal exposure can arise for the employer?','None — references are always protected','Liability for negligent or defamatory misstatement','Only an obligation to re-hire the employee','A criminal fine under the Penal Code only',1,'Employers can face liability in defamation or negligent misstatement for false or misleading references that damage an employee''s prospects.','Labour Law in Zambia: An Introduction, Ch.3',''),

-- LEVEL 7
('l7-q1',7,'An employer deducts money from an employee''s wage to cover a loss that has not been proved against the employee.','Under the Act, when may an employer make deductions from wages?','Whenever the employer suspects wrongdoing','Only as permitted by the Act, a court order, or written agreement with the employee','Only if the employee owes money to a third party','Deductions are never permitted under any circumstance',1,'Deductions are lawful only where authorised by the Act, a court order, or a written employee agreement.','Employment Code Act, 2019, s.68',''),
('l7-q2',7,'A worker works nine hours on a normal working day. The standard working day is eight hours.','How should the extra hour be treated under the Act?','It is treated as a gift to the employer','It must be compensated as overtime at the prescribed rate','The employer may bank the hour for future use without extra pay','Only hours above twelve trigger overtime',1,'Hours worked beyond the normal working hours must be compensated as overtime at the prescribed statutory rate.','Employment Code Act, 2019, s.75',''),
('l7-q3',7,'An employer pays all workers below the national minimum wage claiming economic hardship.','Can an employer lawfully pay below the prescribed minimum wage?','Yes, if the business is in financial difficulty','No — the minimum wage is a statutory floor that cannot be contracted out of','Yes, for employees on probation','Yes, if both parties agree in writing',1,'The prescribed minimum wage is a statutory minimum; paying below it is unlawful regardless of agreement or financial hardship.','Employment Code Act, 2019, s.72 and related SIs',''),
('l7-q4',7,'An employer pays wages in goods rather than money.','What does the Act say about payment of wages in kind?','In-kind payment is freely permitted if the employee agrees','The Act requires wages to be paid in legal tender; in-kind payments are strictly regulated','Goods-based wages are standard in the agricultural sector only','Only foreign currency payment is regulated',1,'The Code requires wages to be paid in legal tender and restricts payment in kind to specific and limited circumstances.','Employment Code Act, 2019, s.69',''),
('l7-q5',7,'An employer fails to keep any wage records and cannot produce payslips for the past year.','What is the employer''s obligation under the Act regarding wage records?','Records are optional if the employer has fewer than ten employees','The employer must keep proper wage records and provide wage statements to employees','Payslips are required only for employees earning above minimum wage','Records only matter if a dispute arises',1,'Employers must maintain proper wage records and provide employees with payslips/wage statements.','Employment Code Act, 2019, s.70',''),

-- LEVEL 8
('l8-q1',8,'An employee has completed twelve months of continuous service and asks for annual leave.','What is the minimum annual leave entitlement under the Act?','Seven working days','Twenty-four working days','It depends entirely on the employment contract','Annual leave only applies to permanent employees earning above minimum wage',1,'Employees are entitled to a minimum of twenty-four working days of annual leave after twelve months of continuous service.','Employment Code Act, 2019, s.36(2)',''),
('l8-q2',8,'A female employee is informed she is entitled to maternity leave but is told it is only forty-two days.','What maternity leave entitlement does the Act provide?','Fourteen days','Ninety days with full pay','Sixty days unpaid','It varies entirely by contract',1,'The Act entitles a female employee to ninety days of maternity leave with full pay.','Employment Code Act, 2019, s.41(1)',''),
('l8-q3',8,'A male employee whose spouse has just given birth asks for paternity leave.','How many days of paternity leave is a male employee entitled to under the Act?','No paternity leave exists under the Act','Five days','Fourteen days','Thirty days',1,'The Act entitles a male employee to five days of paternity leave.','Employment Code Act, 2019, s.42',''),
('l8-q4',8,'An employee has been ill for thirty days in a year and the employer refuses to pay sick leave beyond fourteen days.','What is the minimum sick leave entitlement under the Act?','Seven days','Ninety days per year, with the first 45 at full pay and the next 45 at half pay','Sick leave is entirely at the employer''s discretion','Only three days with pay',1,'Employees are entitled to a minimum of ninety days of sick leave per calendar year, with the first forty-five at full pay and the next forty-five at half pay.','Employment Code Act, 2019, s.38',''),
('l8-q5',8,'An employer forces workers to take annual leave at a time that suits only the employer with no consultation.','What must an employer do before requiring employees to take leave at a particular time?','Nothing — the employer controls when leave is taken','Consult with the employee or employee representative and give reasonable notice','Get Labour Commissioner approval first','Give thirty days written notice to the government',1,'Employers must consult before compelling workers to take leave at a particular time.','Employment Code Act, 2019, s.36(5)',''),
('l8-q6',8,'An employee''s immediate family member has died and the employee requests compassionate leave.','What does the Act say about compassionate and family responsibility leave?','No compassionate leave is mandated','Employees are entitled to compassionate leave in defined circumstances of family bereavement or responsibility','Compassionate leave is only for managers','It requires a court order to access',1,'The Act provides for compassionate and family responsibility leave in circumstances such as bereavement of immediate family.','Employment Code Act, 2019, s.40',''),

-- LEVEL 9
('l9-q1',9,'An employer recruits a worker from a distant district and later dismisses the worker without paying repatriation costs.','What repatriation obligation does the Act place on an employer?','None — repatriation is entirely the worker''s responsibility','The employer must meet repatriation costs where the employer recruited the worker from elsewhere','Repatriation applies only to expatriates','The employer pays only if the worker has worked more than five years',1,'Where an employer recruited a worker away from the worker''s home area, the employer bears repatriation costs on termination.','Employment Code Act, 2019, s.76',''),
('l9-q2',9,'A long-term contract employee completes their full contract term and asks for gratuity.','At what minimum rate is gratuity payable under the Act for a completed long-term contract?','Ten percent of total earnings','Twenty-five percent of the basic pay earned during the contract','One month''s gross pay per year worked','Gratuity is optional at employer discretion',1,'Gratuity is payable at not less than twenty-five percent of the basic pay earned during the contract period.','Employment Code Act, 2019, s.73',''),
('l9-q3',9,'A worker is required to travel away from their normal workstation for three days on company business.','What allowance is the employee entitled to claim?','No allowance — travel is implied in all jobs','A subsistence allowance for each day away from base','Only a transport allowance for the first day','Overtime pay only',1,'Employees required to work away from their normal workstation are entitled to a subsistence allowance for each day away.','Employment Code Act, 2019, s.78',''),
('l9-q4',9,'An employer provides free accommodation to an employee but then reduces the cash salary without consultation.','Is housing accommodation a benefit that can offset cash wage obligations?','Yes — housing can freely replace cash wage at any value the employer chooses','Housing may be part of the remuneration package but must meet prescribed standards and the employee must agree','Housing is irrelevant to employment law','Cash wages can always be replaced by benefits in full',1,'Housing may form part of remuneration under the Act, but it must meet prescribed standards, be agreed upon, and cannot be used to unilaterally cut cash wages below statutory minimums.','Employment Code Act, 2019, s.77',''),

-- LEVEL 10
('l10-q1',10,'An employer wants to dismiss a worker for stealing company equipment caught on CCTV.','Even where clear evidence exists, what procedural step must precede dismissal?','No procedure needed when evidence is strong','A fair disciplinary hearing at which the employee can respond','A police report and conviction first','A warning letter followed by a six-month suspension',1,'In Protea Hotels Zambia v Longa William Mulikelela, the Court of Appeal dismissed the employer''s appeal and upheld compensation, confirming that skipping the hearing made the dismissal unlawful regardless of the evidence.','Employment Code Act, 2019, s.52(3)','Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116'),
('l10-q2',10,'An employee receives a first and only warning for a minor rule infraction and is immediately dismissed.','Why is this dismissal likely to be unfair?','First warnings always justify dismissal','Dismissal is disproportionate; progressive discipline should ordinarily be followed for minor infractions','Only the Labour Commissioner can dismiss for rule infractions','The Act bans all warnings',1,'For minor misconduct, progressive discipline (warnings before dismissal) is expected; instant dismissal would be disproportionate.','Employment Code Act, 2019, s.52; Labour Law in Zambia, Ch.5',''),
('l10-q3',10,'An employer suspends a worker without pay pending a disciplinary investigation.','What is the general rule about suspension pending investigation?','Suspension without pay is always allowed','Suspension should normally be on full pay unless the Act or contract expressly allows otherwise','The employer may suspend without pay whenever convenient','Suspension automatically terminates the contract',1,'Suspending an employee pending investigation should ordinarily be on full pay; suspension without pay requires express contractual or statutory authority.','Employment Code Act, 2019, s.52; Labour Law in Zambia, Ch.5',''),
('l10-q4',10,'An employee is charged with a criminal offence unrelated to employment. The employer dismisses them immediately.','Does a criminal charge alone justify immediate dismissal?','Yes — any criminal charge allows instant dismissal','No — the employer must assess relevance to employment and still follow a fair process','Yes — criminal charges are always gross misconduct','No — but the employer may cut wages while charges are pending',1,'A criminal charge alone does not justify dismissal; the employer must consider whether the charge relates to the employment and follow fair procedure.','Employment Code Act, 2019, s.52; Labour Law in Zambia, Ch.5',''),
('l10-q5',10,'A disciplinary panel includes the employee''s direct line manager who witnessed the alleged misconduct and reported it.','What natural-justice principle is engaged here?','None — managers must always sit on panels','The rule against bias (nemo judex in causa sua) — a witness should not sit as a judge','Only external adjudicators can rule on misconduct','The panel composition never affects validity',1,'Natural justice requires that a panel member who is a witness or who has a direct interest should not also sit as a decision-maker.','Employment Code Act, 2019, s.52(3); Labour Law in Zambia, Ch.5',''),

-- LEVEL 11
('l11-q1',11,'An employer refuses to promote a qualified woman because of assumptions about her family responsibilities.','Which ground of discrimination is most directly at issue?','Discrimination on the ground of sex or gender','Discrimination based on working hours only','A neutral business decision with no legal concern','Discrimination based on educational qualifications',0,'Refusing promotion based on assumptions about a woman''s family responsibilities is sex/gender-based discrimination under the Act.','Employment Code Act, 2019, s.5',''),
('l11-q2',11,'A worker with a disability is denied reasonable accommodation and is placed at a structural disadvantage compared to non-disabled colleagues.','What type of discrimination does this describe?','Direct discrimination','Indirect discrimination or failure to provide reasonable accommodation','No discrimination — disability is not a protected ground','Only a health-and-safety issue',1,'Failure to accommodate a person with a disability and placing them at a structural disadvantage is a form of indirect discrimination and violates the duty of reasonable accommodation.','Employment Code Act, 2019, s.5; Disabilities Act, s.35',''),
('l11-q3',11,'A manager repeatedly makes sexually suggestive comments to a subordinate at work despite the subordinate''s clear discomfort.','How does the Act characterise this conduct?','A minor workplace relationship issue only','Sexual harassment — a form of workplace discrimination prohibited under the Act','A personal matter outside employment law','Only criminal if physical contact occurs',1,'Sexual harassment is a prohibited form of workplace discrimination under the Employment Code Act.','Employment Code Act, 2019, s.5(6)',''),
('l11-q4',11,'An employer applies a facially neutral requirement that in practice excludes significantly more women than men with no business justification.','What concept does this illustrate?','Direct discrimination','Indirect discrimination','Reverse discrimination','Positive action',1,'Indirect discrimination arises when a neutral rule disproportionately disadvantages a protected group without objective justification.','Employment Code Act, 2019, s.5; Labour Law in Zambia, Ch.6',''),
('l11-q5',11,'An employer dismisses an employee after the employee discloses their HIV-positive status.','How does the Employment Code Act treat this dismissal?','It may be lawful if the role requires physical fitness','It is prohibited — dismissal on the grounds of HIV status is unlawful discrimination','Only the Workers'' Compensation Act governs this','The employer must prove the dismissal was for a different reason, which courts always accept',1,'HIV status is a protected ground; dismissing an employee on account of HIV status is unlawful discrimination.','Employment Code Act, 2019, s.5 and s.95',''),

-- LEVEL 12
('l12-q1',12,'An employer wants to employ a child aged thirteen in a light, non-hazardous task during school holidays with parental consent.','What is the minimum age for employment under the Employment Code Act?','Twelve years','Fifteen years','Eighteen years','Sixteen years',1,'The Act sets fifteen as the minimum employment age for light, non-hazardous work.','Employment Code Act, 2019, s.106',''),
('l12-q2',12,'An employer wants to have a seventeen-year-old work in a mine handling explosives.','Is this permissible under Zambian law?','Yes, if the minor is supervised','No — hazardous work is prohibited for persons under eighteen','Yes, if parental consent is given','Yes, for mining specifically',1,'Hazardous work is prohibited for persons under the age of eighteen.','Employment Code Act, 2019, s.106; Labour Law in Zambia, Ch.7',''),
('l12-q3',12,'An employer requires a sixteen-year-old employee to work night shifts starting at 10 pm.','What does the law say about night work for persons under eighteen?','Night work is freely permitted for all employees','Night work is prohibited for persons under eighteen except in specified circumstances','Only persons under fifteen may not work nights','Night work restrictions apply only to females under eighteen',1,'Night work for persons under eighteen is prohibited except in specific legally permitted circumstances.','Employment Code Act, 2019, s.104; Labour Law in Zambia, Ch.7',''),
('l12-q4',12,'An apprentice asks whether the Employment Code Act governs their training arrangement.','Which statute primarily governs apprenticeships in Zambia?','The Employment Code Act, 2019 alone','The Apprenticeship Act, Chapter 275 of the Laws of Zambia','The Skills Development Levy Act','The Workers'' Compensation Act',1,'Apprenticeships are primarily governed by the Apprenticeship Act, Chapter 275, which sets out the formal training framework.','Apprenticeship Act, Cap 275; Labour Law in Zambia, Ch.7',''),

-- LEVEL 13
('l13-q1',13,'An employer has not been registering its employees with NAPSA since the company opened two years ago.','What is the employer''s primary obligation under NAPSA legislation?','Registration is optional for companies with fewer than twenty employees','Every employer must register with NAPSA and make prescribed monthly contributions','NAPSA only covers public servants','Registration is required only at retirement of the employee',1,'Employers are legally required to register with NAPSA and remit monthly contributions for all eligible employees.','National Pension Scheme Act; Labour Law in Zambia, Ch.9',''),
('l13-q2',13,'An employer asks whether the National Health Insurance Act requires mandatory enrolment.','Is NHIMA registration mandatory for employers?','No — NHIMA is voluntary','Yes — the National Health Insurance Act requires employers to register and contribute','Only for companies with more than fifty employees','Only for the public sector',1,'The National Health Insurance Act mandates employer and employee contributions to the National Health Insurance scheme.','National Health Insurance Act, 2018; Labour Law in Zambia, Ch.9',''),
('l13-q3',13,'An employee is injured at work and asks what statutory scheme covers compensation for that injury.','Which legislation governs compensation for work-related injuries and diseases in Zambia?','The Employment Code Act, 2019','The Workers'' Compensation Act','The NAPSA Act','The Gender Equality Act',1,'The Workers'' Compensation Act governs compensation for employees injured or who contract diseases arising from their employment.','Workers'' Compensation Act, No 10 of 1999',''),
('l13-q4',13,'An employer has not paid the Skills Development Levy for two years.','Under which Act is the Skills Development Levy required?','The Employment Code Act','The Skills Development Levy Act, 2016','The Industrial and Labour Relations Act','The Penal Code',1,'The Skills Development Levy Act, No 46 of 2016, requires employers to pay the levy.','Skills Development Levy Act, No 46 of 2016',''),
('l13-q5',13,'An employer asks whether NAPSA contributions are required for a fixed-term contract employee who has worked for six months.','Are fixed-term employees covered by NAPSA?','No — only permanent employees are covered','Yes — NAPSA contributions are required for all eligible employees regardless of contract type','Only after twelve months of continuous service','Only if the employee earns above minimum wage',1,'NAPSA coverage applies to all eligible employees regardless of whether the contract is permanent or fixed-term.','National Pension Scheme Act; Labour Law in Zambia, Ch.9',''),

-- LEVEL 14
('l14-q1',14,'Workers at a company want to form a trade union. The employer says only one union can exist in any industry.','What is the general principle on union formation under the ILRA?','Only one union per enterprise is ever permitted','Workers have the right to organise and form or join trade unions freely','Employers may prohibit union formation if they offer good conditions','Unions are only permitted in the public sector',1,'The ILRA protects the right to organise and join trade unions as a fundamental right.','ILRA, s.5; Labour Law in Zambia, Ch.8',''),
('l14-q2',14,'A union and an employer negotiate a collective agreement that sets wages above the statutory minimum.','What is the legal status of a registered collective agreement?','It has the same force as a gentleman''s agreement only','A registered collective agreement is legally binding on all parties covered by it','It binds only union members who signed it','Collective agreements are always subordinate to individual contracts',1,'A registered collective agreement is legally binding and its terms are incorporated into individual contracts of employment.','ILRA, s.71; Labour Law in Zambia, Ch.8',''),
('l14-q3',14,'Workers go on an unprotected strike without following the statutory dispute resolution procedure.','What is the key legal consequence of an unprotected strike?','Strikers are immune from any action','Employees participating in an unprotected strike may face disciplinary action including dismissal','The employer must negotiate immediately','The Labour Commissioner must arbitrate within one day',1,'Employees engaged in an unprotected (unlawful) strike lose statutory protection and can be dismissed.','ILRA, s.108; Labour Law in Zambia, Ch.8',''),
('l14-q4',14,'An employer refuses to recognise a union that has recruited more than half the employees as members.','What obligation does the ILRA impose on the employer?','None — recognition is voluntary','The employer must recognise the union once it meets the recognition threshold','The employer must first seek court approval','The employer may delay recognition for two years',1,'Once a union meets the statutory recognition threshold, the employer is obliged to recognise it under the ILRA.','ILRA, s.23(1); Labour Law in Zambia, Ch.8',''),

-- LEVEL 15
('l15-q1',15,'An employee has been dismissed unfairly and wants to challenge the dismissal. Their legal adviser asks which forum has primary jurisdiction.','Which tribunal has primary jurisdiction over unfair dismissal disputes in Zambia?','The Magistrate''s Court','The Industrial Relations Division of the High Court','The Constitutional Court only','The Zambia Arbitration Centre',1,'The Industrial Relations Division of the High Court has primary jurisdiction over employment disputes including unfair dismissal.','ILRA, s.85A; Labour Law in Zambia, Ch.10',''),
('l15-q2',15,'A dispute arises and the parties want to try mediation before going to court.','What role does the Labour Commissioner play in employment dispute resolution?','The Labour Commissioner only enforces criminal sanctions','The Labour Commissioner provides conciliation and mediation services before disputes proceed to adjudication','The Labour Commissioner has no dispute-resolution function','The Labour Commissioner can issue binding arbitration awards without consent',1,'The Labour Commissioner provides conciliation and mediation to help resolve disputes before they escalate to the Industrial Relations Court.','ILRA; Labour Law in Zambia, Ch.10',''),
('l15-q3',15,'A dismissed employee wins a case for wrongful dismissal. The court considers what remedy to award.','What are the main remedies available for wrongful dismissal in Zambia?','Only a written apology','Reinstatement, re-engagement, or compensation','Only criminal prosecution of the employer','The court can only award reinstatement',1,'In Zulu & Another v Barclays Bank of Zambia Limited, the Supreme Court engaged with the question of reasons and appropriate remedies, confirming that a wrongful dismissal finding opens the door to meaningful compensation.','Employment Code Act, 2019, s.52(4); Labour Law in Zambia, Ch.10','Zulu & Another v Barclays Bank of Zambia Limited [2003] ZMSC 95'),
('l15-q4',15,'An employer argues that a dispute must go straight to the High Court without any prior conciliation attempt.','What does the ILRA require before a matter proceeds to adjudication?','Nothing — parties can go straight to court','The parties must first attempt conciliation through the Labour Commissioner','Only a letter of demand is needed','A police report must be filed first',1,'The ILRA requires parties to attempt conciliation before proceeding to formal adjudication in the Industrial Relations Court.','ILRA; Labour Law in Zambia, Ch.10',''),

-- LEVEL 16
('l16-q1',16,'An employer fills a vacancy with a foreign national even though a suitably qualified Zambian citizen applied for the role.','Which principle under the Employment Code Act is most directly violated?','The gratuity provisions','The citizen priority principle — citizens must be preferred where suitably qualified','The redundancy notice provisions','The leave entitlement provisions',1,'The Act requires employers to give citizen priority when filling vacancies; expatriates may only be engaged where no suitably qualified citizen is available.','Employment Code Act, 2019, s.14',''),
('l16-q2',16,'An employment agency wants to send a Zambian worker to work abroad under a contract that has not yet been secured or bonded.','What power does an authorised officer have before attesting such a contract?','No power at all once travel is booked','Power to require security by bond or cash deposit to guarantee performance','Power only to suggest a hotel booking','Power only after the worker has already left the country',1,'Before attesting an outside-Republic employment contract, an authorised officer may require security by bond or cash deposit.','Employment Code Act, 2019, s.30',''),
('l16-q3',16,'An expatriate employee asks whether the Employment Code Act applies to them.','Does the Employment Code Act apply to expatriate employees working in Zambia?','No — it only applies to Zambian citizens','Yes — the Act applies to employees regardless of nationality working in Zambia','Only if their work permit says so','Only after five years of residence',1,'The Act applies to all employees working in Zambia, regardless of nationality, subject to specific exclusions.','Employment Code Act, 2019, s.2',''),

-- LEVEL 17
('l17-q1',17,'A factory worker is injured when unsafe machinery the employer knew about causes an accident.','Which employer common-law duty and statutory provision are most directly engaged?','Only the minimum-wage provisions','The duty to provide a safe system of work and safe equipment, reinforced by OHS legislation','Only the redundancy provisions','Only the maternity leave provisions',1,'Employers owe a common-law and statutory duty to provide safe equipment and a safe system of work.','Occupational Health and Safety Act, 2010; Labour Law in Zambia, Ch.3',''),
('l17-q2',17,'An employer with fifty or more employees has no HIV and AIDS workplace policy.','What does the Employment Code Act require regarding workplace HIV/AIDS policies?','An HIV and AIDS policy is optional','An employer must ensure an HIV and AIDS policy exists in the undertaking','Only hospitals must have such policies','The policy is required only where workers have tested positive',1,'The Act requires every employer to ensure an HIV and AIDS workplace policy exists.','Employment Code Act, 2019, s.95',''),
('l17-q3',17,'An employee is dismissed after disclosing their HIV-positive status to the employer.','How does the Employment Code Act treat this dismissal?','It may be lawful if the role requires physical fitness','It is prohibited — dismissal on the grounds of HIV status is unlawful discrimination','Only the Workers'' Compensation Act governs this situation','The employer must prove the dismissal was for a different reason, which is always accepted',1,'HIV status is a protected ground; dismissing an employee on account of HIV status is unlawful discrimination.','Employment Code Act, 2019, s.5 and s.95',''),

-- LEVEL 18
('l18-q1',18,'A court needs to decide whether a premature end of a long-term contract attracts prorated gratuity.','Which case directly addresses prorated gratuity on early termination of a long-term contract?','Oliver Zimba and Ors v Kay Two Zambia Limited','Tinashe Timothy Gandize v Newrest Zambia Limited [2023] ZMHC 53','Harrison Phiri v Akaal Engineering Limited','Redrilza v Nkazi',1,'In Tinashe Timothy Gandize v Newrest Zambia Limited, the court ordered prorated gratuity under s.53(6) calculated on the period actually worked, plus outstanding wages. The case is the clearest authority that early termination does not forfeit the employee''s right to a proportional gratuity.','Employment Code Act, 2019, s.53(6)','Tinashe Timothy Gandize v Newrest Zambia Limited [2023] ZMHC 53'),
('l18-q2',18,'An employer argues procedural fairness is irrelevant once misconduct is clearly established.','Which 2025 Court of Appeal case most directly rejects that argument?','Sandie Mkandawire v Trinity University','Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116','Francis Machakube and Ors v City University of Science and Technology','Esau Shamalambo v China Zambia Friendship Farm Ltd',1,'The Court of Appeal dismissed Protea Hotels'' appeal in full, holding that the right to a fair hearing before dismissal is unconditional and cannot be defeated by pointing to evidence of wrongdoing. The damages award to the employee was upheld.','Employment Code Act, 2019, s.52(3)','Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116'),
('l18-q3',18,'An employee was retaliatorily dismissed after suing the employer over unpaid wages; natural-justice principles were also ignored.','Which 2024 High Court case best addresses retaliatory dismissal and natural-justice remedies?','Oliver Zimba and Ors v Kay Two Zambia Limited','Jimmy Mulusa v First National Bank Zambia Limited','Francis Machakube and Ors v City University of Science and Technology [2024] ZMHC 115','Walter Anderson v ASF Zambia Hotel Holding Ltd',2,'The court found the dismissals retaliatory and procedurally defective (no hearing), awarding back pay for the unlawful dismissal period and full terminal entitlements to all claimants.','Employment Code Act, 2019, s.52(3)–(4)','Francis Machakube and Ors v City University of Science and Technology [2024] ZMHC 115'),
('l18-q4',18,'An employee resigned but then claimed the employer had effectively forced the resignation and also withheld terminal entitlements.','Which 2024 case is most useful on constructive-dismissal-type arguments and post-resignation disputes?','Tinashe Timothy Gandize v Newrest Zambia Limited','Harrison Phiri v Akaal Engineering Limited','Walter Anderson v ASF Zambia Hotel Holding Ltd [2024] ZMHC 234','Sandie Mkandawire v Trinity University',2,'In Walter Anderson v ASF Zambia Hotel Holding Ltd, the court found in favour of the employee on the post-resignation entitlement issues and ordered outstanding dues to be paid.','Employment Code Act, 2019, ss.52–54','Walter Anderson v ASF Zambia Hotel Holding Ltd [2024] ZMHC 234'),
('l18-q5',18,'A dispute involves gratuity calculation and deductions from terminal dues after a long-term contract.','Which 2024 High Court case is particularly useful on gratuity calculation method and deductions?','Jimmy Mulusa v First National Bank Zambia Limited','Esau Shamalambo v China Zambia Friendship Farm Ltd','Turnvell Mataa Sendoi v Interlink Freight Services Limited [2024] ZMHC 140','Redrilza v Nkazi',2,'The court upheld gratuity, struck out the unauthorised deductions, but the overtime claim failed because the employee lacked evidence to prove hours and quantum. A reminder that every head of claim must be proved independently.','Employment Code Act, 2019, ss.53, 54, 68, 73','Turnvell Mataa Sendoi v Interlink Freight Services Limited [2024] ZMHC 140'),
('l18-q6',18,'In Oliver Zimba and Ors v Kay Two Zambia Limited [2023] ZMHC 42, the employer effected a redundancy and failed to pay packages on the employees'' last day of duty.','What did the court actually order?','Immediate reinstatement of all employees','The employer must continue paying employees'' full wages until every redundancy package is fully settled','A lump-sum penalty of three months'' gross pay per employee','The case was dismissed because operational reasons were proved',1,'The court applied s.55(3)(b) directly: because packages were not paid by the last day of duty, the employer was ordered to keep paying full wages to all affected employees until every package was settled.','Employment Code Act, 2019, ss.55(2) and 55(3)(b)','Oliver Zimba and Ors v Kay Two Zambia Limited [2023] ZMHC 42'),
('l18-q7',18,'In Harrison Phiri v Akaal Engineering Limited [2024] ZMHC 258, the employer argued that withholding terminal benefits was justified because of an ongoing internal dispute.','How did the court rule?','The court agreed — an ongoing dispute can justify withholding benefits pending resolution','The court found the withholding unlawful and ordered full payment of all outstanding statutory dues','The court ordered a three-month mediation period before any award','The court partially upheld the withholding for items the employer could itemise',1,'The court was unambiguous: a pending internal dispute gives an employer no licence to withhold statutory terminal benefits. Full payment was ordered.','Employment Code Act, 2019, ss.52–54','Harrison Phiri v Akaal Engineering Limited [2024] ZMHC 258'),
('l18-q8',18,'In Turnvell Mataa Sendoi v Interlink Freight Services Limited [2024] ZMHC 140, the employee claimed gratuity, overtime, and challenged deductions from terminal dues.','Which of the three heads of claim actually failed, and why?','Gratuity failed — the contract was short-term','Overtime failed — the employee could not produce sufficient evidence of the hours worked and quantum','The deduction challenge failed — the employer produced valid invoices','All three claims succeeded in full',1,'The court upheld gratuity and struck down the unauthorised deductions — but overtime failed because the employee lacked evidence. Every head of claim must be proved independently.','Employment Code Act, 2019, ss.68, 73, 75','Turnvell Mataa Sendoi v Interlink Freight Services Limited [2024] ZMHC 140'),
('l18-q9',18,'In Esau Shamalambo v China Zambia Friendship Farm Ltd [2024] ZMHC 230, the employer labelled the separation a voluntary resignation.','What did the court find and award?','The court accepted the resignation label and dismissed the claim','The court looked past the label, found the employee had been dismissed, and awarded notice pay and all accrued terminal entitlements','The court found a genuine resignation but awarded an ex gratia payment only','The court ordered re-engagement at a different farm',1,'The court refused to accept the employer''s characterisation at face value, examined the actual circumstances, found a dismissal, and awarded notice pay plus all accrued terminal entitlements.','Employment Code Act, 2019, ss.52 and 53','Esau Shamalambo v China Zambia Friendship Farm Ltd [2024] ZMHC 230'),
('l18-q10',18,'In Francis Machakube and Ors v City University of Science and Technology [2024] ZMHC 115, several lecturers were dismissed after initiating litigation over unpaid wages.','What did the court order?','Reinstatement only, with no monetary award','Both substantive and procedural grounds of dismissal were found unlawful; the court awarded back pay and full terminal entitlements to all claimants','The claim was dismissed — prior litigation by employees disentitles them to relief','An apology and a formal warning letter to the employer''s HR director',1,'The court found the dismissals retaliatory and procedurally defective. It awarded back pay and full terminal entitlements. This is the leading 2024 authority against employer retaliation for employees asserting statutory wage rights.','Employment Code Act, 2019, s.52(3)–(4)','Francis Machakube and Ors v City University of Science and Technology [2024] ZMHC 115'),

-- LEVEL 19
('l19-q1',19,'A worker on a fixed-term contract is dismissed without hearing, has unpaid wages, and has unused annual leave when the employment ends mid-contract.','Which combination of entitlements is most likely at issue?','Only gratuity','Wrongful dismissal remedy, unpaid wages, accrued leave pay, and gratuity','Only the gratuity and nothing else','Only unpaid wages; leave and gratuity do not arise on fixed-term contracts',1,'In Sandie Mkandawire v Trinity University, the court awarded all four heads: compensation for wrongful dismissal, unpaid wages, accrued annual leave pay, and gratuity at 25% of basic pay earned up to termination.','Employment Code Act, 2019, ss.36, 52, 54','Sandie Mkandawire v Trinity University [2025] ZMHC 55'),
('l19-q2',19,'An employer restructures, declares redundancy without sixty-days notice, and then fills the same vacancy four months later without offering it to the redundant employee first.','How many statutory breaches are present in this scenario?','None — the employer was reorganising legitimately','Two — failure to give sixty-days notice and failure to offer the vacancy back to the redundant employee within nine months','Only one — the notice failure','One — but only the failure to re-offer matters',1,'Two distinct breaches: the sixty-days notice requirement under s.55(2) and the re-employment priority obligation under s.57.','Employment Code Act, 2019, ss.55(2) and 57','Oliver Zimba and Ors v Kay Two Zambia Limited [2023] ZMHC 42'),
('l19-q3',19,'An employee claims she was constructively dismissed after her salary was cut unilaterally, her leave request was denied, and she was then placed on a performance improvement plan in retaliation for complaining.','Which body of legal principles is central to evaluating her claim?','Redundancy law only','Contract variation, the implied duty of trust and confidence, and procedural fairness in dismissal','Only the leave entitlement sections','Collective bargaining law only',1,'Constructive dismissal claims turn on whether the employer''s conduct breached a fundamental term — here the salary cut, leave denial, and retaliatory PIP all engage contract variation, the trust-and-confidence duty, and fair process.','Employment Code Act, 2019, ss.25, 36, 52; Labour Law in Zambia, Ch.2 and Ch.5',''),
('l19-q4',19,'A foreign national works in Zambia without a valid work permit. The employer argues the employment contract is void and therefore no terminal benefits are owed.','Can the employer rely on the illegal contract defence to avoid paying terminal benefits?','Yes — an illegal contract is always void and no claims can arise','Possibly not — courts may still protect the worker''s accrued statutory entitlements despite permit irregularities','Yes — this is settled law in Zambia','No — but only if the employee is a SADC national',1,'Even where a work permit irregularity exists, Zambian courts may still protect a worker''s accrued statutory rights; the illegality defence is not automatically available to defeat terminal claims.','Employment Code Act, 2019, s.2; Labour Law in Zambia, Ch.2',''),
('l19-q5',19,'A worker is dismissed, has not been paid wages for two months, has unused sick leave, and was never given a certificate of service.','Which four statutory rights are simultaneously engaged?','Only the certificate of service obligation','Unfair dismissal, unpaid wages, sick leave balance, and certificate of service','Only the wage and certificate issues','Only the dismissal and leave issues',1,'All four statutory obligations are engaged: fair dismissal procedure (s.52), unpaid wages (s.68), sick leave balance (s.38), and certificate of service (s.59).','Employment Code Act, 2019, ss.38, 52, 59, 68',''),
('l19-q6',19,'An employer dismisses a worker during a protected strike that followed a properly declared trade dispute.','Are these workers protected from dismissal for that action?','No — any industrial action justifies dismissal','Possibly yes — if the dispute was properly declared and the action is protected, workers retain statutory protection','Only union officials are protected','Yes — all industrial action is always protected regardless of procedure',1,'Workers engaged in lawful industrial action following a properly declared trade dispute enjoy statutory protection; the employer cannot use dismissal as a weapon against protected strike action.','ILRA, s.108; Labour Law in Zambia, Ch.8',''),

-- LEVEL 20
('l20-q1',20,'An employee on permanent terms is given one month''s notice of termination after working for twelve years. The employer says no gratuity is owed because the Act only covers fixed-term contracts.','Is the employer correct?','Yes — gratuity only applies to fixed-duration contracts','No — long service gratuity or terminal benefits may still be owed to permanent employees on termination','Yes — twelve years is below the threshold','No — but only if the employee is in a union',1,'Terminal benefits for permanent employees are not confined to fixed-term gratuity; the employer''s sweeping exclusion is wrong.','Employment Code Act, 2019, ss.52–54, 73',''),
('l20-q2',20,'A female employee returns from maternity leave to find her position filled and no equivalent role offered.','Which combined statutory protections are most engaged?','Only the leave entitlement sections','Maternity protection (s.43), non-discrimination (s.5), and fair dismissal procedure (s.52)','Only the redundancy provisions','Only the probation provisions',1,'The scenario engages maternity protection, sex discrimination, and unfair dismissal; all three must be assessed together.','Employment Code Act, 2019, ss.5, 43, 52',''),
('l20-q3',20,'An employer dismissed workers for participating in a go-slow that was preceded by a properly declared trade dispute.','Are these workers protected from dismissal for that action?','No — any slowdown justifies dismissal','Possibly yes — if the dispute was properly declared and the action does not cross into unprotected strike territory, workers may retain protection','Only union officials are protected','Yes — all industrial action is always protected',1,'Workers engaged in lawful industrial action following a properly declared trade dispute enjoy statutory protection; whether a go-slow qualifies requires analysis of whether it is protected action.','ILRA, s.108; Labour Law in Zambia, Ch.8',''),
('l20-q4',20,'An employer claims it does not need to consult employees'' union before a mass redundancy because consultation is only required by collective agreements, not statute.','Is this correct?','Yes — statutory consultation on redundancy is optional','No — the Employment Code Act requires consultation and sixty-days notice to an authorised officer before effecting redundancy','Yes — only if the union has fewer than ten members at the undertaking','Correct — the sixty-days notice goes to NAPSA, not an authorised officer',1,'The Act independently requires consultation and sixty-days prior notice to an authorised officer; this is a statutory obligation, not merely a collective-agreement term.','Employment Code Act, 2019, s.55(2)','Oliver Zimba and Ors v Kay Two Zambia Limited [2023] ZMHC 42'),
('l20-q5',20,'A junior HR officer asks: if an employee commits gross misconduct AND is owed unpaid wages, can the employer set off those wages against any damages owed?','What is the legally cautious answer?','Always yes — misconduct automatically forfeits all wages','Possibly, but only where the Act or a court order authorises the deduction; wages are not automatically forfeited due to misconduct','Always no — wages can never be set off','Only if the employee agrees in writing at the time of hiring',1,'Wages are a statutory entitlement; misconduct does not automatically extinguish them. Set-off or deductions require lawful authority under s.68 of the Act.','Employment Code Act, 2019, s.68','Turnvell Mataa Sendoi v Interlink Freight Services Limited [2024] ZMHC 140'),
('l20-q6',20,'An employment lawyer argues that Zambia''s courts should look at South African and UK employment law when Zambian statute is silent on an issue.','On what constitutional basis can foreign law inform Zambian employment law?','There is no constitutional basis for using foreign law','The Constitution''s interpretation clause allows courts to consider comparable foreign jurisdictions and international law as persuasive authority','Only SADC member-state law is relevant','Only UK law is relevant because Zambia is a common-law jurisdiction',1,'Zambia''s Constitution allows courts to draw on international and foreign law as persuasive authority when interpreting rights; this is especially relevant for gaps in employment statute.','Constitution of Zambia; Labour Law in Zambia, Ch.1',''),
('l20-q7',20,'In Sandie Mkandawire v Trinity University [2025] ZMHC 55, the court had to calculate gratuity for an employee dismissed mid-way through a fixed-term contract without a hearing.','On what basis and at what rate did the court calculate gratuity?','Gross pay over the entire projected contract term at 10%','25% of basic pay actually earned from contract start to the termination date, per s.54(1)(c)','One month''s salary per year of service at any rate the court chose','No gratuity — the contract was less than two years so no entitlement arose',1,'The court applied s.54(1)(c) precisely: 25% of the basic pay earned from commencement to termination date — not the full projected contract value, and not zero.','Employment Code Act, 2019, s.54(1)(c)','Sandie Mkandawire v Trinity University [2025] ZMHC 55'),
('l20-q8',20,'Protea Hotels Zambia appealed to the Court of Appeal in Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116, arguing strong misconduct evidence should override the need for a fair hearing.','What did the Court of Appeal decide?','Appeal succeeded — strong misconduct evidence makes procedural requirements discretionary','Appeal dismissed — the right to a fair hearing before dismissal is unconditional; evidence strength does not remove the obligation','The court remitted the case for a fresh hearing without an award','The damages award was reduced by 50% as a compromise',1,'The Court of Appeal dismissed the appeal. The core holding: procedural fairness is not contingent on how strong the case against the employee is. The original damages award was upheld.','Employment Code Act, 2019, s.52(3)','Protea Hotels Zambia v Longa William Mulikelela [2025] ZMCA 116'),
('l20-q9',20,'In Tinashe Timothy Gandize v Newrest Zambia Limited [2023] ZMHC 53, the employer argued no gratuity was owed because the long-term contract was terminated early, before completion.','How did the court respond to that argument?','Agreed — gratuity only crystallises when a long-term contract runs to its full term','Rejected entirely: s.53(6) expressly provides prorated gratuity based on the period actually worked; the court ordered payment on that basis','Ordered reinstatement in lieu of any gratuity','Awarded the full contract-term gratuity as a penalty for early termination',1,'The court was direct: s.53(6) exists to prevent employers from escaping gratuity liability by terminating early. Prorated gratuity on the service period actually rendered was ordered, together with outstanding wages.','Employment Code Act, 2019, s.53(6)','Tinashe Timothy Gandize v Newrest Zambia Limited [2023] ZMHC 53'),
('l20-q10',20,'In Jimmy Mulusa v First National Bank Zambia Limited [2024] ZMHC 184, FNB relied solely on a stated "operational requirement" to justify termination and argued no further scrutiny was warranted.','What did the court decide on that justification?','FNB''s justification was accepted — courts do not second-guess business reorganisation decisions','FNB failed to substantiate the operational requirement; the court found wrongful termination and awarded compensation','The court deferred entirely to FNB''s business judgment but required a written apology','The court found for FNB on substance but awarded ex gratia pay as a compromise',1,'Applying s.52(2), the court found FNB had produced no evidence that a genuine reorganisation existed or that Mulusa''s position was genuinely redundant. Merely asserting "operational requirements" is insufficient — they must be proved.','Employment Code Act, 2019, s.52(2)','Jimmy Mulusa v First National Bank Zambia Limited [2024] ZMHC 184')

on conflict (id) do update set
  level           = excluded.level,
  scenario        = excluded.scenario,
  question        = excluded.question,
  option_a        = excluded.option_a,
  option_b        = excluded.option_b,
  option_c        = excluded.option_c,
  option_d        = excluded.option_d,
  correct_index   = excluded.correct_index,
  explanation     = excluded.explanation,
  act_reference   = excluded.act_reference,
  case_reference  = excluded.case_reference;
